/-
# MiniModuleTheory: Subobjects

Subobject constructions for module theory.
-/

import MiniModuleTheory.Core.Basic
import MiniModuleTheory.Core.Objects

namespace MiniModuleTheory

/-! ## Submodule Generated by a Set -/

def submoduleGeneratedBy (R : Ring) (M : Module R) (S : Set M.carrier) : Submodule R M :=
  { subset := S
    zero_mem := sorry
    add_closed := sorry
    smul_closed := sorry
  }

/-! ## Annihilator of a Module -/

def annihilator (R : Ring) (M : Module R) : Set R.carrier :=
  fun r => ∀ (x : M.carrier), M.smul r x = M.zero

/-! ## Torsion Submodule -/

def torsionSubmodule (R : Ring) (M : Module R) : Submodule R M where
  subset := fun x => ∃ (r : R.carrier), r ≠ R.zero ∧ M.smul r x = M.zero
  zero_mem := ⟨R.zero, by
    -- need a proof that R.zero ≠ R.zero is false, but we need r ≠ R.zero
    sorry⟩
  add_closed := sorry
  smul_closed := sorry

end MiniModuleTheory
