/-
# Tests.Examples

Step-by-step Galois theory constructions.
-/

import MiniGaloisTheoryLite

open MiniGaloisTheoryLite

/-! ## Step 1: Define a Galois group -/

#eval "Step 1: GaloisGroup with automorphisms and group structure defined"

/-! ## Step 2: State normality and separability axioms -/

#eval s!"Step 2: Galois extension axioms: {galoisExtensionAxioms.length}"

/-! ## Step 3: Build the Galois correspondence -/

#eval s!"Step 3: Galois correspondence (bijection + inclusion-reversing + normal): {galoisCorrespondenceAxioms.length} axioms"

/-! ## Step 4: State the Fundamental Theorem -/

#eval s!"Step 4: FTGT: intermediate fields <-> subgroups, order-reversing, degree = index, normal = normal"

/-! ## Step 5: Construct a cyclotomic extension -/

#eval s!"Step 5: Gal(Q(zeta_n)/Q) ~= (Z/nZ)^x, degree = phi(n)"

/-! ## Step 6: Construct a finite field extension -/

#eval s!"Step 6: Gal(F_{p^n}/F_p) ~= C_n, generated by Frobenius"

/-! ## Step 7: State solvability by radicals -/

#eval s!"Step 7: Solvable by radicals iff solvable Galois group. S_5 insolvable -> quintic not solvable"

/-! ## Summary -/

#eval "=== All 7 steps completed ==="
#eval s!"Package axioms total: {galoisTheoryTotalAxioms.length}"
