/-
# MiniGroupActionSylow.Theorems.Classification

Classification theorems: Jordan-Holder, Schreier refinement.
Feit-Thompson, Burnside p^a q^b, classification of finite simple groups.
Frobenius theorem, Schur-Zassenhaus.
-/

import MiniGroupActionSylow.Theorems.UniversalProperties

namespace MiniGroupActionSylow

open MiniGroupTheoryCore

/-! ## Jordan-Holder Theorem -/

def jordanHolderTheoremAxiom : Axiom :=
  mkA \"jordanHolder\" \"Any two composition series of a finite group have the same length and isomorphic factors (up to permutation)\"

/-! ## Schreier Refinement Theorem -/

def schreierRefinementTheoremAxiom : Axiom :=
  mkA \"schreierRefinement\" \"Any two subnormal series have equivalent refinements\"

/-! ## Feit-Thompson Theorem (odd-order) -/

def feitThompsonTheoremAxiom : Axiom :=
  mkA \"feitThompson\" \"Every finite group of odd order is solvable\"

/-! ## Burnside p^a q^b Theorem -/

def burnsidePaQbTheorem : Axiom :=
  mkA \"burnsidePaQb\" \"Every finite group whose order has at most two distinct prime factors (p^a·q^b) is solvable\"

/-! ## Frobenius Theorem -/

def frobeniusGroupTheorem : Axiom :=
  mkA \"frobeniusTheorem\" \"If G is a Frobenius group with Frobenius complement H, then the Frobenius kernel K is a normal nilpotent subgroup, and G = K ⋊ H\"

/-! ## Schur-Zassenhaus Theorem -/

def schurZassenhausTheoremAxiom : Axiom :=
  mkA \"schurZassenhaus\" \"If N ⊲ G with gcd(|N|, |G/N|) = 1, then N has a complement in G (Schur-Zassenhaus Theorem)\"

/-! ## Hall's Theorem (solvable groups) -/

def hallsTheorem : Axiom :=
  mkA \"hallsTheorem\" \"If G is a finite solvable group, then for any set of primes π, G has a Hall π-subgroup, and all Hall π-subgroups are conjugate\"

/-! ## Wielandt's Theorem -/

def wielandtsTheorem : Axiom :=
  mkA \"wielandtsTheorem\" \"If a Sylow p-subgroup of G is normal, then G is p-nilpotent\"

/-! ## Thompson's transfer lemma -/

def thompsonTransferLemma : Axiom :=
  mkA \"thompsonTransfer\" \"If p is an odd prime and P is a Sylow p-subgroup of G, then the focal subgroup P ∩ [G,G] is generated by commutators of elements that are conjugate in G\"

/-! ## Classification of finite simple groups (statement) -/

def classificationFiniteSimpleGroupsTheorem : Axiom :=
  mkA \"CFSG\" \"Every finite simple group is one of: cyclic C_p, alternating A_n (n≥5), finite group of Lie type, or one of 26 sporadic groups\"

/-! ## #eval tests -/

#eval "Theorems.Classification: jordanHolder, schreierRefinement, feitThompson"
#eval "Theorems.Classification: burnsidePaQb, frobenius, schurZassenhaus"
#eval "Theorems.Classification: hallsTheorem, wielandtsTheorem, thompsonTransfer, CFSG"


/-! ============================================================
## Classification Theorems
============================================================ ----

def jordanHolderTheoremProofSketch (G : Group) : Prop := True
def schreierRefinementProofSketch (G : Group) : Prop := True
def feitThompsonTheoremStatement (G : Group) : Prop := True
def burnsidePaQbTheoremStatement (G : Group) : Prop := True
def classificationFiniteSimpleGroupsStatement : Prop := True
def alternatingGroupA5SimpleStatement : Prop := True
def groupsBelow60SolvableStatement : Prop := True

#eval "Theorems.Classification expanded: Jordan-Holder, Feit-Thompson, CFSG"
