/-
# MiniGroupActionSylow.Theorems.Classification

Classification theorems: Jordan-Holder, Schreier refinement.
Feit-Thompson, Burnside p^a q^b, classification of finite simple groups.
Frobenius theorem, Schur-Zassenhaus.
-/

import MiniGroupActionSylow.Theorems.UniversalProperties

namespace MiniGroupActionSylow

open MiniGroupTheoryCore

/-! ## Jordan-Holder Theorem -/

def jordanHolderTheoremAxiom : Axiom :=
  Axiom.mk "jordanHolder" (Formula.pred 0 [])
    "Any two composition series of a finite group have the same length and isomorphic factors (up to permutation)"

/-! ## Schreier Refinement Theorem -/

def schreierRefinementTheoremAxiom : Axiom :=
  Axiom.mk "schreierRefinement" (Formula.pred 0 [])
    "Any two subnormal series have equivalent refinements"

/-! ## Feit-Thompson Theorem (odd-order) -/

def feitThompsonTheoremAxiom : Axiom :=
  Axiom.mk "feitThompson" (Formula.pred 0 [])
    "Every finite group of odd order is solvable"

/-! ## Burnside p^a q^b Theorem -/

def burnsidePaQbTheorem : Axiom :=
  Axiom.mk "burnsidePaQb" (Formula.pred 0 [])
    "Every finite group whose order has at most two distinct prime factors (p^a·q^b) is solvable"

/-! ## Frobenius Theorem -/

def frobeniusGroupTheorem : Axiom :=
  Axiom.mk "frobeniusTheorem" (Formula.pred 0 [])
    "If G is a Frobenius group with Frobenius complement H, then the Frobenius kernel K is a normal nilpotent subgroup, and G = K ⋊ H"

/-! ## Schur-Zassenhaus Theorem -/

def schurZassenhausTheoremAxiom : Axiom :=
  Axiom.mk "schurZassenhaus" (Formula.pred 0 [])
    "If N ⊲ G with gcd(|N|, |G/N|) = 1, then N has a complement in G (Schur-Zassenhaus Theorem)"

/-! ## Hall's Theorem (solvable groups) -/

def hallsTheorem : Axiom :=
  Axiom.mk "hallsTheorem" (Formula.pred 0 [])
    "If G is a finite solvable group, then for any set of primes π, G has a Hall π-subgroup, and all Hall π-subgroups are conjugate"

/-! ## Wielandt's Theorem -/

def wielandtsTheorem : Axiom :=
  Axiom.mk "wielandtsTheorem" (Formula.pred 0 [])
    "If a Sylow p-subgroup of G is normal, then G is p-nilpotent"

/-! ## Thompson's transfer lemma -/

def thompsonTransferLemma : Axiom :=
  Axiom.mk "thompsonTransfer" (Formula.pred 0 [])
    "If p is an odd prime and P is a Sylow p-subgroup of G, then the focal subgroup P ∩ [G,G] is generated by commutators of elements that are conjugate in G"

/-! ## Classification of finite simple groups (statement) -/

def classificationFiniteSimpleGroupsTheorem : Axiom :=
  Axiom.mk "CFSG" (Formula.pred 0 [])
    "Every finite simple group is one of: cyclic C_p, alternating A_n (n≥5), finite group of Lie type, or one of 26 sporadic groups"

/-! ## #eval tests -/

#eval "Theorems.Classification: jordanHolder, schreierRefinement, feitThompson"
#eval "Theorems.Classification: burnsidePaQb, frobenius, schurZassenhaus"
#eval "Theorems.Classification: hallsTheorem, wielandtsTheorem, thompsonTransfer, CFSG"
