/-
# MiniGroupActionSylow.Theorems.UniversalProperties

Universal properties of semi-direct products, group presentations.
Free group universal property. Orbit category.
-/

import MiniGroupActionSylow.Theorems.Basic

namespace MiniGroupActionSylow

open MiniGroupTheoryCore

/-! ## Semi-direct product universal property -/

def semidirectProductUniversal : Axiom :=
  Axiom.mk "semidirectProductUniversal" (Formula.pred 0 [])
    "N ⋊_φ H is the unique group (up to iso) with N ⊲ G, H < G, G = NH, N ∩ H = {1}, and conjugation on N matches φ"

/-! ## Free group universal property -/

def freeGroupUniversal : Axiom :=
  Axiom.mk "freeGroupUniversal" (Formula.pred 0 [])
    "For any set X, the free group F(X) satisfies: any map X → G extends uniquely to a homomorphism F(X) → G"

/-! ## Group presentation universal property -/

def groupPresentationUniversal : Axiom :=
  Axiom.mk "groupPresentationUniversal" (Formula.pred 0 [])
    "⟨S | R⟩ is the unique group (up to iso) generated by S satisfying relations R, universal among groups with generators satisfying R"

/-! ## Orbit category -/

def orbitCategoryUniversal : Axiom :=
  Axiom.mk "orbitCategoryUniversal" (Formula.pred 0 [])
    "Orbit category O(G) has objects G/H for H≤G and morphisms the equivariant maps. The Yoneda embedding classifies all G-sets"

/-! ## Equivariant Yoneda lemma -/

def equivariantYoneda : Axiom :=
  Axiom.mk "equivariantYoneda" (Formula.pred 0 [])
    "For any G-set X and subgroup H, Hom_G(G/H, X) ≅ X^H (the H-fixed points)"

/-! ## Burnside ring universal property -/

def burnsideRingUniversal : Axiom :=
  Axiom.mk "burnsideRingUniversal" (Formula.pred 0 [])
    "The Burnside ring Ω(G) is the Grothendieck ring of finite G-sets under disjoint union and cartesian product"

/-! ## Tensor-Hom adjunction for G-sets -/

def gSetTensorHomAdjunction : Axiom :=
  Axiom.mk "gSetTHAdjunction" (Formula.pred 0 [])
    "For G-sets X, Y, Z: Hom_G(X × Y, Z) ≅ Hom_G(X, Hom(Y, Z)) with conjugation action on Hom"

/-! ## #eval tests -/

#eval "Theorems.UniversalProperties: semidirectProductUniversal, freeGroupUniversal"
#eval "Theorems.UniversalProperties: groupPresentationUniversal, orbitCategoryUniversal"
#eval "Theorems.UniversalProperties: equivariantYoneda, burnsideRingUniversal, gSetTensorHomAdjunction"
