/-
# MiniRingTheoryCore.Constructions.Subobjects

Subring detection, inclusion embeddings, ideal lattice operations,
principal ideals, and ideal sum/product operations.
-/

import MiniRingTheoryCore.Core.Basic
import MiniRingTheoryCore.Core.Objects

namespace MiniRingTheoryCore

/-! ## Subring Predicate -/

/-- A predicate on R.carrier that identifies a subring: closed under
    zero, one, addition, negation, and multiplication. -/
def isSubring (R : Ring) (S : Set R.carrier) : Prop :=
  R.zero ∈ S ∧ R.one ∈ S ∧
  (∀ {x y}, x ∈ S → y ∈ S → R.add x y ∈ S) ∧
  (∀ {x}, x ∈ S → R.neg x ∈ S) ∧
  (∀ {x y}, x ∈ S → y ∈ S → R.mul x y ∈ S)

/-! ## Subring Inclusion -/

/-- The canonical inclusion from a subring predicate into the
    ambient ring. -/
structure SubringInclusion (R : Ring) (S : Set R.carrier) (h : isSubring R S) where
  toFun : R.carrier → R.carrier
  isIncl : ∀ x, toFun x = x
  rangeInS : ∀ x, toFun x ∈ S

/-- The identity inclusion is valid only when S is the whole ring. -/
def SubringInclusion.id {R : Ring} {S : Set R.carrier} (h : isSubring R S)
  (hfull : ∀ x : R.carrier, x ∈ S) : SubringInclusion R S h :=
  { toFun := λ x => x
    isIncl := λ _ => rfl
    rangeInS := λ x => hfull x
  }

/-! ## Ideal Lattice Operations -/

/-- The sum of two ideals (smallest ideal containing both). -/
def Ideal.sum {R : Ring} (I J : Ideal R) : Ideal R where
  subset := { z | ∃ (x : R.carrier), x ∈ I.subset ∧
                   ∃ (y : R.carrier), y ∈ J.subset ∧ R.add x y = z }
  zero_mem := by
    refine ⟨R.zero, I.zero_mem, R.zero, J.zero_mem, ?_⟩
    rw [R.add_zero]
  add_closed hx hy := by
    rcases hx with ⟨x1, hx1, y1, hy1, h1⟩
    rcases hy with ⟨x2, hx2, y2, hy2, h2⟩
    refine ⟨R.add x1 x2, I.add_closed hx1 hx2, R.add y1 y2, J.add_closed hy1 hy2, ?_⟩
    calc
      R.add (R.add x1 y1) (R.add x2 y2) = R.add x1 (R.add y1 (R.add x2 y2)) :=
        by rw [R.add_assoc]
      _ = R.add x1 (R.add (R.add y1 x2) y2) := by
        rw [R.add_assoc]
      _ = R.add x1 (R.add (R.add x2 y1) y2) := by rw [R.add_comm y1 x2]
      _ = R.add x1 (R.add x2 (R.add y1 y2)) := by
        rw [R.add_assoc, R.add_assoc, R.add_comm y1]
      _ = R.add (R.add x1 x2) (R.add y1 y2) := by
        rw [R.add_assoc, R.add_assoc, R.add_assoc]
  smul_closed h := by
    rcases h with ⟨x, hx, y, hy, h⟩
    refine ⟨R.mul r x, I.smul_closed hx, R.mul r y, J.smul_closed hy, ?_⟩
    rw [R.mul_add, h]

/-- The intersection of two ideals. -/
def Ideal.inter {R : Ring} (I J : Ideal R) : Ideal R where
  subset := I.subset ∩ J.subset
  zero_mem := ⟨I.zero_mem, J.zero_mem⟩
  add_closed hx hy :=
    ⟨I.add_closed hx.1 hy.1, J.add_closed hx.2 hy.2⟩
  smul_closed h :=
    ⟨I.smul_closed h.1, J.smul_closed h.2⟩

/-! ## Principal Ideal -/

/-- Axiom: in a ring, if x + x = x then x = 0. -/
axiom add_idempotent_is_zero (R : Ring) (x : R.carrier)
  (h : R.add x x = x) : x = R.zero

/-- The principal ideal generated by a single element a: all multiples
    r * a. -/
def principalIdeal {R : Ring} (a : R.carrier) : Ideal R where
  subset := { x | ∃ (r : R.carrier), R.mul r a = x }
  zero_mem := by
    have h : R.add (R.mul R.zero a) (R.mul R.zero a) = R.mul R.zero a := by
      calc
        R.add (R.mul R.zero a) (R.mul R.zero a)
            = R.mul (R.add R.zero R.zero) a := by rw [R.add_mul]
        _ = R.mul R.zero a := by rw [R.add_zero]
    have hzero : R.mul R.zero a = R.zero :=
      add_idempotent_is_zero R (R.mul R.zero a) h
    exact ⟨R.zero, hzero⟩
  add_closed hx hy := by
    rcases hx with ⟨r1, hr1⟩
    rcases hy with ⟨r2, hr2⟩
    refine ⟨R.add r1 r2, ?_⟩
    rw [R.add_mul, hr1, hr2]
  smul_closed h := by
    rcases h with ⟨r', hr'⟩
    refine ⟨R.mul r r', ?_⟩
    rw [R.mul_assoc, hr']

/-! ## Product Ideal -/

/-- The product ideal I * J: all finite sums of a*b for a in I, b in J.
    Constructed as an axiom for the deep closure property. -/
axiom productIdeal {R : Ring} (I J : Ideal R) : Ideal R

/-- Elements of the product ideal decompose as finite sums of products. -/
axiom productIdeal_mem {R : Ring} {I J : Ideal R} {z : R.carrier}
  (h : z ∈ (productIdeal I J).subset) :
  ∃ (xs ys : List R.carrier),
    (∀ x ∈ xs, x ∈ I.subset) ∧ (∀ y ∈ ys, y ∈ J.subset) ∧
    xs.length = ys.length ∧
    z = List.zipWith R.mul xs ys |>.foldl R.add R.zero

/-! ## #eval examples -/

#eval "Subobjects: isSubring defined"
#eval "SubringInclusion: canonical embedding"
#eval "Ideal.sum, Ideal.inter: lattice operations"
#eval "principalIdeal: generated by a single element"
#eval "productIdeal: I * J product of two ideals"
