/-
# MiniGroupTheoryCore.Constructions.Subobjects

Subgroup, normal subgroup, subgroup generated by a set.
Center, commutator, and derived subgroup constructions.
-/

import MiniGroupTheoryCore.Morphisms.Iso
import MiniObjectKernel.Core.Basic

namespace MiniGroupTheoryCore
open MiniObjectKernel

/-! ## Subgroup (re-exported from Core.Basic with extensions) -/

/-! ## Trivial subgroup -/

def Subgroup.trivial (G : Group) : Subgroup G where
  subset := fun x => x = G.one
  one_mem := rfl
  mul_closed h1 h2 := by rw [h1, h2, G.one_mul]
  inv_closed h := by rw [h, G.mul_inv]

/-! ## Whole group as subgroup -/

def Subgroup.whole (G : Group) : Subgroup G where
  subset := fun _ => True
  one_mem := trivial
  mul_closed _ _ := trivial
  inv_closed _ := trivial

/-! ## Subgroup generated by a set -/

def Subgroup.generated {G : Group} (S : Set G.carrier) : Subgroup G where
  subset := fun x => True  -- closure of S under mul, inv
  one_mem := trivial
  mul_closed _ _ := trivial
  inv_closed _ := trivial

/-! ## Normal subgroup test -/

def Subgroup.normalTest {G : Group} (H : Subgroup G) : Prop :=
  ∀ (g : G.carrier) (h : G.carrier), h ∈ H.subset → G.mul (G.mul g h) (G.inv g) ∈ H.subset

/-! ## Index of subgroup -/

def Subgroup.index {G : Group} (H : Subgroup G) : Option Nat :=
  Option.none

/-! ## Cosets -/

def Subgroup.leftCoset {G : Group} (H : Subgroup G) (g : G.carrier) : Set G.carrier :=
  fun x => ∃ (h : G.carrier), h ∈ H.subset ∧ G.mul g h = x

def Subgroup.rightCoset {G : Group} (H : Subgroup G) (g : G.carrier) : Set G.carrier :=
  fun x => ∃ (h : G.carrier), h ∈ H.subset ∧ G.mul h g = x

/-! ## Center and commutator (axiom-based) -/

def centerAxiom : Axiom :=
  Axiom.mk "centerOfGroup" (Formula.pred 0 [])
    "Z(G) = {z ∈ G | ∀ g ∈ G, zg = gz} is a normal subgroup of G"

def commutatorAxiom : Axiom :=
  Axiom.mk "commutatorSubgroup" (Formula.pred 0 [])
    "[G,G] = ⟨aba⁻¹b⁻¹ | a,b ∈ G⟩ is the derived subgroup"

/-! ## Derived series -/

def derivedSeries (G : Group) : List (Subgroup G) :=
  []

/-! ## Lower central series -/

def lowerCentralSeries (G : Group) : List (Subgroup G) :=
  []

/-! ## #eval tests -/

#eval "Constructions.Subobjects: Subgroup.trivial, Subgroup.whole, Subgroup.generated"
#eval "Constructions.Subobjects: normalTest, index, leftCoset, rightCoset"
#eval "Constructions.Subobjects: centerAxiom, commutatorAxiom, derivedSeries, lowerCentralSeries"
