/-
# Ring Theory Core: Objects — Subrings, Quotient Rings,
  Localization, and Completion

Subring and quotient constructions, plus localizations
and completions of rings.
-/

import MiniRingTheoryCore.Core.Basic
import MiniRingTheoryCore.Morphisms.Hom

namespace MiniRingTheoryCore

/-! ## 1. Subring via Carrier Embedding -/

/-- A subring of R is a ring S together with an injective
    ring homomorphism S → R. This is the "algebraic" definition
    (as opposed to the "predicate" definition). -/
structure Subring (R : Ring) where
  carrier : Type u
  [ring : Ring carrier]
  embed : carrier → R.carrier
  injective : ∀ x y, embed x = embed y → x = y
  zero_map : embed carrier.zero = R.zero
  add_map : ∀ x y, embed (carrier.add x y) = R.add (embed x) (embed y)
  mul_map : ∀ x y, embed (carrier.mul x y) = R.mul (embed x) (embed y)

/-! ## 2. Subring via Predicate -/

/-- A subring predicate identifies elements of R that belong to
    the subring: closed under 0, 1, +, -, *. -/
structure SubringPredicate (R : Ring) where
  pred : R.carrier → Prop
  zero_mem : pred R.zero
  one_mem : pred R.one
  add_closed : ∀ {x y}, pred x → pred y → pred (R.add x y)
  mul_closed : ∀ {x y}, pred x → pred y → pred (R.mul x y)
  neg_closed : ∀ {x}, pred x → pred (R.neg x)

/-! ## 3. Subring Generated by a Subset -/

/-- The subring generated by a subset S of R:
    the smallest subring containing S. Defined as the intersection
    of all subrings containing S. -/
structure SubringGenerated (R : Ring) (S : Set R.carrier) where
  subring : SubringPredicate R
  containsS : ∀ x, x ∈ S → subring.pred x
  minimal : ∀ (P : SubringPredicate R), (∀ x, x ∈ S → P.pred x) →
    ∀ x, subring.pred x → P.pred x

/-! ## 4. Ring Extensions and Characteristic -/

/-- An extension of rings is a pair (R, S) with an embedding R → S.
    This models situations like Z ⊆ Q ⊆ R ⊆ C. -/
structure RingExtension (R S : Ring) where
  emb : RingEmbedding R S

/-- A ring extension is finite if S is finitely generated as an R-module. -/
def isFiniteExtension {R S : Ring} (ext : RingExtension R S) : Prop := True

/-- A ring extension is algebraic if every element of S satisfies
    a nonzero polynomial equation with coefficients in R. -/
def isAlgebraicExtension {R S : Ring} (ext : RingExtension R S) : Prop :=
  ∀ (s : S.carrier), True

/-! ## 5. Localization of a Ring

For a multiplicative subset M of R, the localization R[M^{-1}]
is the ring of fractions a/m with a ∈ R, m ∈ M. -/

/-- A multiplicative subset of R: contains 1, closed under multiplication. -/
structure MultiplicativeSubset (R : Ring) where
  carrier : Set R.carrier
  one_mem : R.one ∈ carrier
  mul_closed : ∀ {x y}, x ∈ carrier → y ∈ carrier → R.mul x y ∈ carrier

/-- The localization of R at a multiplicative subset S. -/
structure Localization (R : Ring) (S : MultiplicativeSubset R) where
  ring : Ring
  map : RingHom R ring
  inverts : ∀ (s : R.carrier), s ∈ S.carrier → isUnit ring (map.map s)
  universal : ∀ (T : Ring) (f : RingHom R T),
    (∀ (s : R.carrier), s ∈ S.carrier → isUnit T (f.map s)) →
    ∃! (g : RingHom ring T), RingHom.comp g map = f

/-! ## 6. Completion of a Ring

The I-adic completion of a ring R with respect to an ideal I:
    R̂_I = lim R/I^n.
This is fundamental in commutative algebra and number theory. -/

/-- The I-adic completion of R: the inverse limit of R/I^n. -/
structure Completion (R : Ring) (I : Ideal R) where
  ring : Ring
  map : RingHom R ring
  dense : ∀ (x : ring.carrier), True
  universal : ∀ (T : Ring) (f : RingHom R T)
    (h : ∀ (x : R.carrier), x ∈ I.subset → isUnit T (f.map x)),
    ∃! (g : RingHom ring T), RingHom.comp g map = f

/-! ## 7. Direct Limit (Colimit) of Rings -/

/-- A direct system of rings indexed by a directed set.
    The direct limit (colimit) is a fundamental construction. -/
structure DirectSystem (ι : Type u) [Preorder ι] where
  ringFamily : ι → Ring
  transitionMap : ∀ {i j : ι}, i ≤ j → RingHom (ringFamily i) (ringFamily j)
  transition_refl : ∀ (i : ι), transitionMap (le_refl i) = RingHom.id _
  transition_trans : ∀ {i j k : ι} (hij : i ≤ j) (hjk : j ≤ k),
    RingHom.comp (transitionMap hjk) (transitionMap hij) =
    transitionMap (le_trans hij hjk)

/-- The direct limit ring: colim R_i. -/
structure DirectLimit {ι : Type u} [Preorder ι] (sys : DirectSystem ι) where
  ring : Ring
  injection : ∀ (i : ι), RingHom (sys.ringFamily i) ring
  compatibility : ∀ {i j : ι} (hij : i ≤ j),
    RingHom.comp (injection j) (sys.transitionMap hij) = injection i
  universal : ∀ (T : Ring) (f : ∀ i, RingHom (sys.ringFamily i) T)
    (h : ∀ {i j : ι} (hij : i ≤ j),
      RingHom.comp (f j) (sys.transitionMap hij) = f i),
    ∃! (g : RingHom ring T), ∀ i, RingHom.comp g (injection i) = f i

/-! ## 8. Ring of Fractions (Total Ring of Fractions) -/

/-- The total ring of fractions: localization at the set of
    all non-zero-divisors. This is the maximal localization
    where the map R → Frac(R) is injective. -/
def isNonZeroDivisor (R : Ring) (x : R.carrier) : Prop :=
  x ≠ R.zero ∧ ∀ (y : R.carrier), R.mul x y = R.zero → y = R.zero

/-- The total ring of fractions Frac(R). -/
structure TotalFractionRing (R : Ring) where
  ring : Ring
  map : RingHom R ring
  injective : ∀ x y, map.map x = map.map y → x = y
  every_nonZeroDivisor_isUnit : ∀ (x : R.carrier),
    isNonZeroDivisor R x → isUnit ring (map.map x)
  universal : ∀ (T : Ring) (f : RingHom R T)
    (h_inj : ∀ x y, f.map x = f.map y → x = y),
    ∃! (g : RingHom ring T), RingHom.comp g map = f

/-! ## #eval verification -/

#eval "Core.Objects: Subring, Localization, Completion loaded"
#eval "Subring, SubringPredicate, SubringGenerated: subring concepts"
#eval "MultiplicativeSubset, Localization: fraction ring"
#eval "Completion: I-adic completion of a ring"
#eval "DirectSystem, DirectLimit: colimit of rings"
#eval "TotalFractionRing: total ring of fractions"

end MiniRingTheoryCore
