/-
# MiniGaloisTheoryLite.Examples.Counterexamples

Galois theory counterexamples: non-Galois extensions,
non-solvable Galois groups, inseparable extensions,
infinite profinite Galois groups, and exotic Galois groups.
-/

import MiniGaloisTheoryLite.Examples.Standard

namespace MiniGaloisTheoryLite

/-! ## Counterexample 1: ℚ(∛2)/ℚ is NOT Galois

ℚ(∛2)/ℚ is not normal because it only contains one of the three
cube roots of 2. The other two (ω·∛2, ω²·∛2) are not in ℚ(∛2).
|Aut_ℚ(ℚ(∛2))| = 1 < [ℚ(∛2):ℚ] = 3.
-/

def nonGaloisCuberoot2 : String :=
  "ℚ(∛2)/ℚ is not Galois: not normal (missing complex cube roots of 2)"

def cuberoot2HasNoNontrivialAutomorphisms : String :=
  "|Aut_ℚ(ℚ(∛2))| = 1 < [ℚ(∛2):ℚ] = 3 ⇒ not Galois"

def galoisClosureOfCuberoot2 : String :=
  "Galois closure is ℚ(∛2, ζ₃) with Galois group S₃ (order 6)"

/-! ## Counterexample 2: S₅ as non-solvable Galois group

x⁵ - 6x + 3 over ℚ has Galois group S₅ (order 120).
S₅ is not solvable: [S₅, S₅] = A₅, [A₅, A₅] = A₅ (simple non-abelian).
Therefore the quintic is not solvable by radicals.
-/

def s5GaloisGroup : String :=
  "x⁵ - 6x + 3 over ℚ has Galois group S₅ (order 120), which is not solvable"

def s5NotSolvableReason : String :=
  "S₅ is not solvable: derived series S₅ > A₅ = A₅ = ... (A₅ is simple non-abelian)"

def s5ConcreteExample : String :=
  "Discriminant of x⁵ - 6x + 3 is not a perfect square → Galois group ≤ S₅ contains an odd permutation. Factorization mod 2, 3, 5, 7, 11 reveals cycle types (5), (3,2), (5), (5), (2,2,1) → Galois group = S₅."

/-! ## Counterexample 3: Inseparable extension in char p

F_p(t)/F_p(t^p) is purely inseparable.
The minimal polynomial of t over F_p(t^p) is x^p - t^p = (x-t)^p,
so it has a repeated root. Hence not separable ⇒ not Galois.
-/

def inseparableExtension : String :=
  "F_p(t)/F_p(t^p) is purely inseparable: minimal polynomial of t is x^p - t^p = (x - t)^p (repeated root)"

def inseparableNotGalois : String :=
  "F_p(t)/F_p(t^p) is not separable → not Galois. |Aut| = 1 but [F_p(t):F_p(t^p)] = p"

def inseparableDegreeIsPowerOfP : String :=
  "Every purely inseparable extension has degree a power of p. The automorphism group is trivial."

/-! ## Counterexample 4: Infinite Galois extension (absolute Galois group)

Gal(ℚ̅/ℚ) is an infinite profinite group.
It is the projective limit: G_ℚ = lim_{E/ℚ finite Galois} Gal(E/ℚ).
The absolute Galois group of F_p is Ẑ = lim ℤ/nℤ, generated by Frobenius.
-/

def absoluteGaloisGroupQ : String :=
  "Gal(ℚ̅/ℚ) is an infinite profinite group: lim_{E/ℚ finite Galois} Gal(E/ℚ)"

def absoluteGaloisGroupFp : String :=
  "Gal(F̅_p/F_p) ≅ Ẑ (profinite completion of ℤ), generated by Frobenius"

def absoluteGaloisGroupOfR : String :=
  "Gal(ℂ/ℝ) ≅ C₂ (the only non-trivial finite Galois extension of ℝ)"

def absoluteGaloisGroupOfC : String :=
  "Gal(ℂ/ℂ) = {1} (ℂ is algebraically closed)"

/-! ## Counterexample 5: Non-abelian simple Galois groups

A₅ (order 60) and PSL(2,7) (order 168) occur as Galois groups
over ℚ. These are the two smallest non-abelian simple groups.
-/

def a5GaloisGroup : String :=
  "A₅ (order 60) occurs as Gal(x⁵ - 5x + 12/ℚ) — smallest non-abelian simple group"

def psl2of7Galois : String :=
  "PSL(2,7) ≅ GL(3,2) (order 168) occurs as Gal(x⁷ - 7x + 3/ℚ) — second smallest"

def monsterGroupGalois : String :=
  "The Monster simple group M (order ≈ 8×10⁵³) is realized as a Galois group over ℚ (Thompson, 1984 via rigidity)"

/-! ## Counterexample 6: Normality is NOT transitive

F ⊆ K ⊆ E with E/F normal does NOT imply K/F normal.
Example: ℚ ⊆ ℚ(√2) ⊆ ℚ(⁴√2). ℚ(⁴√2)/ℚ is normal (splitting field of x⁴-2),
but ℚ(√2)/ℚ is also normal. A better counterexample: ...

Actually, the classic example is:
ℚ ⊆ ℚ(∛2) ⊆ ℚ(∛2, ζ₃). The big extension is Galois (closure),
but ℚ(∛2)/ℚ is not normal.
-/

def normalityNotTransitiveExample : String :=
  "ℚ ⊆ ℚ(∛2) ⊆ ℚ(∛2, ζ₃): the big one is Galois, but ℚ(∛2)/ℚ is not normal"

/-! ## Counterexample 7: Separability is NOT preserved upward

If E/K is not separable and K/F is not separable, then E/F may still be
not separable. But the key point is: separability of E/F does NOT pull
back to intermediate extensions in characteristic p.
-/

def separabilityCounterexample : String :=
  "In characteristic p: F_p(t^p) ⊆ F_p(t) ⊆ F_p(t^{1/p}).
   F_p(t^{1/p})/F_p(t^p) is inseparable (degree p²), but each step is degree p."

/-! ## Counterexample 8: Galois group not determining the field

Two different number fields can have the same Galois group.
Example (Dedekind): ℚ(⁴√-6) and ℚ(√-2, √-3) both have Galois group D₄
but are not isomorphic (different discriminants).
-/

def galoisGroupNotDeterminingField : String :=
  "ℚ(⁴√-6)/ℚ and ℚ(√-2, √-3)/ℚ both have Galois group D₄ but are not isomorphic extensions of ℚ"

/-! ## Counterexample 9: Infinite algebraic extension not Galois

ℚ̅/ℚ is a normal separable algebraic extension but infinite
(not finite-dimensional). The Galois correspondence still holds
with Krull topology on the Galois group.
-/

def infiniteAlgebraicNotFiniteGalois : String :=
  "ℚ̅/ℚ is infinite algebraic, normal, separable, but not finite Galois. Gal(ℚ̅/ℚ) is profinite."

/-! ## Counterexample 10: Transcendental extension

ℚ(π)/ℚ is transcendental (not algebraic). It is not Galois
in the usual sense. The automorphism group Aut(ℚ(π)/ℚ) is huge
and not related to [ℚ(π):ℚ] = ∞.
-/

def transcendentalExtension : String :=
  "ℚ(π)/ℚ is transcendental. trdeg = 1, [ℚ(π):ℚ] = ∞. Aut(ℚ(π)/ℚ) is the Cremona group (huge)."

/-! ## Counterexample 11: Non-isomorphic Galois groups from isomorphisms

Field isomorphisms don't lift to Galois group isomorphisms in general.
-/

def nonLiftingIsomorphism : String :=
  "Two isomorphic extensions may have non-isomorphic Galois closures.
   Example: ℚ(√2) and ℚ(√3) are both C₂-extensions over ℚ and are isomorphic
   as extensions, but their embeddings differ."

/-! ## Counterexample 12: Cebotarev counterexample

Not every conjugacy class of the Galois group occurs as the Frobenius
of a prime ideal (only those that are unramified).
-/

def ramifiedPrimesNoFrobenius : String :=
  "Primes ramified in the extension do not have a well-defined Frobenius conjugacy class.
   Example: For ℚ(ζ_p)/ℚ, only p is ramified."

/-! ## Counterexample 13: Torsion in absolute Galois group

Gal(ℚ̅/ℚ) has non-trivial torsion elements (elements of finite order)?
Artin-Schreier: the only possible finite order in the absolute Galois
group of a field is 2 (by Artin-Schreier theorem).
-/

def artinSchreierTorsion : String :=
  "Theorem of Artin-Schreier: If Gal(F̅/F) has a non-trivial finite subgroup, then:
   (1) The subgroup has order 2; (2) F is real closed. Example: Gal(ℂ/ℝ) ≅ C₂."

/-! ## Counterexample 14: p-adic Galois groups

Gal(ℚ̅_p/ℚ_p) is much smaller than Gal(ℚ̅/ℚ), making p-adic Galois
representations a powerful tool.
-/

def padicGaloisGroup : String :=
  "Gal(ℚ̅_p/ℚ_p) is a finitely generated profinite group (Jannsen-Wingberg).
   This is much smaller than Gal(ℚ̅/ℚ), making local-to-global principles possible."

/-! ## Counterexamples summary -/

structure GaloisCounterexample where
  name : String
  description : String
  violatesProperty : String

def counterexamplesList : List GaloisCounterexample := [
  { name := "ℚ(∛2)/ℚ",
    description := nonGaloisCuberoot2,
    violatesProperty := "Normality (and hence Galois property)" },
  { name := "x⁵-6x+3 over ℚ",
    description := s5GaloisGroup,
    violatesProperty := "Solvability by radicals" },
  { name := "F_p(t)/F_p(t^p)",
    description := inseparableExtension,
    violatesProperty := "Separability" },
  { name := "ℚ̅/ℚ",
    description := absoluteGaloisGroupQ,
    violatesProperty := "Finiteness (infinite-dimensional)" },
  { name := "A₅ over ℚ",
    description := a5GaloisGroup,
    violatesProperty := "Not solvable, but still a Galois group" },
  { name := "ℚ(⁴√-6) vs ℚ(√-2,√-3)",
    description := galoisGroupNotDeterminingField,
    violatesProperty := "Uniqueness (same Galois group, different fields)" }
]

/-! ## #eval tests -/

#eval "Examples.Counterexamples: nonGaloisCuberoot2, s5GaloisGroup, inseparableExtension"
#eval "Examples.Counterexamples: absoluteGaloisGroupQ, a5GaloisGroup, psl2of7"
#eval "Examples.Counterexamples: normalityNotTransitive, separabilityCounterexample"
#eval "Examples.Counterexamples: galoisGroupNotDeterminingField, transcendentalExtension"
#eval s!"Total counterexamples: {counterexamplesList.length}"
#eval "Examples.Counterexamples: artinSchreierTorsion, padicGaloisGroup"
