/-
# MiniGaloisTheoryLite.Examples.Counterexamples

Galois theory counterexamples: non-Galois extensions,
non-solvable Galois groups, inseparable extensions,
transcendental extensions.
-/

import MiniGaloisTheoryLite.Examples.Standard
import MiniGroupTheoryCore.Core.Basic
import MiniFieldTheoryCore.Core.Basic

namespace MiniGaloisTheoryLite

open MiniGroupTheoryCore
open MiniFieldTheoryCore

/-! ## Non-Galois extension: Q(cuberoot(2)) -/

def nonGaloisCuberoot2 : String :=
  "Q(2^(1/3))/Q is not Galois: it is not normal because the other cube roots (omega * 2^(1/3), omega^2 * 2^(1/3)) are not in Q(2^(1/3))"

def cuberoot2HasNoAutomorphisms : String :=
  "|Aut_Q(Q(2^(1/3)))| = 1 < [Q(2^(1/3)):Q] = 3, so not Galois"

/-! ## S_5 Galois group (insolvable quintic) -/

def s5GaloisGroup : String :=
  "The polynomial x^5 - 6x + 3 over Q has Galois group S_5 (order 120), which is not solvable"

def s5NotSolvableReason : String :=
  "S_5 is not solvable because its derived series does not terminate at the identity: [S_5, S_5] = A_5, [A_5, A_5] = A_5 (A_5 is simple non-abelian)"

/-! ## Inseparable extension in characteristic p -/

def inseparableExtension : String :=
  "F_p(t)/F_p(t^p) is purely inseparable: the minimal polynomial of t is x^p - t^p = (x - t)^p, so it has a repeated root"

def inseparableNotGalois : String :=
  "F_p(t)/F_p(t^p) is not separable, hence not Galois"

/-! ## Infinite Galois extension: absolute Galois group -/

def absoluteGaloisGroupQ : String :=
  "Gal(Q^alg/Q) is an infinite profinite group. It is a projective limit: lim Gal(E/Q) over finite Galois extensions E/Q"

def absoluteGaloisGroupFp : String :=
  "Gal(Fbar_p/F_p) ~= Zhat (the profinite completion of Z), generated by Frobenius"

/-! ## Non-abelian simple Galois group -/

def a5GaloisGroup : String :=
  "A_5 (order 60) can occur as a Galois group over Q. Example: the splitting field of a suitable quintic"

def psl2of7 : String :=
  "PSL(2,7) = GL(3,2) (order 168) occurs as Gal(x^7 - 7x + 3 / Q) — the second smallest non-abelian simple group"

/-! ## Counterexamples summary -/

def counterexamplesGaloisLite : String :=
  "Q(2^(1/3)) non-Galois | S_5 insolvable | F_p(t)/F_p(t^p) inseparable | Q^alg/Q infinite profinite | A_5 and PSL(2,7) as Galois groups"

/-! ## #eval tests -/

#eval "Examples.Counterexamples: nonGaloisCuberoot2, s5GaloisGroup, inseparableExtension"
#eval "Examples.Counterexamples: absoluteGaloisGroupQ, a5GaloisGroup, psl2of7"
#eval s!"Counterexamples: {counterexamplesGaloisLite}"
