/-
# MiniGaloisTheoryLite.Examples.Standard

Standard Galois theory examples: quadratic extensions,
cyclotomic extensions, biquadratic extensions,
finite fields, cubic extensions, Kummer extensions.
-/

import MiniGaloisTheoryLite.Theorems.Main
import MiniGroupTheoryCore.Core.Basic
import MiniFieldTheoryCore.Core.Basic

namespace MiniGaloisTheoryLite

open MiniGroupTheoryCore
open MiniFieldTheoryCore

/-! ## Quadratic extension Q(sqrt(d)) -/

def quadraticExtensionExample (d : Nat) : FieldExtension :=
  -- Q(sqrt(d))/Q, Galois group C_2
  sorry

/-! ## Biquadratic extension Q(sqrt(2), sqrt(3)) -/

def biquadraticExtensionExample : FieldExtension :=
  -- Gal(Q(sqrt(2), sqrt(3))/Q) ~= C_2 x C_2 (Vierergruppe)
  sorry

def biquadraticGaloisGroup : String :=
  "C_2 x C_2 (Klein four-group V4). Subgroup lattice: 3 subgroups of order 2, corresponding to Q(sqrt(2)), Q(sqrt(3)), Q(sqrt(6))"

/-! ## Cyclotomic extension Q(zeta_n) -/

def cyclotomicExtensionQ (n : Nat) : FieldExtension :=
  -- Q(zeta_n)/Q, Galois group (Z/nZ)^x
  sorry

def cyclotomicExample5 : String :=
  "Gal(Q(zeta_5)/Q) ~= (Z/5Z)^x ~= C_4. Subfield: Q(sqrt(5)) corresponding to the subgroup of squares."

def cyclotomicExample7 : String :=
  "Gal(Q(zeta_7)/Q) ~= (Z/7Z)^x ~= C_6. Subfields: Q(sqrt(-7)) corresponding to subgroup of order 3"

/-! ## Cubic extension Q(cuberoot(2)) -/

def cubicExtensionNonGalois : FieldExtension :=
  -- Q(2^(1/3))/Q, not Galois (not normal, missing complex roots)
  sorry

def cubicGaloisClosure : String :=
  "The Galois closure of Q(2^(1/3)) is Q(2^(1/3), zeta_3) with Galois group S_3"

/-! ## Finite field extension F_{p^n}/F_p -/

def finiteFieldExtension (p n : Nat) : FieldExtension :=
  -- F_{p^n}/F_p, Galois group C_n
  sorry

def finiteFieldFrobenius : String :=
  "Gal(F_{p^n}/F_p) is generated by Frobenius automorphism phi(x) = x^p, order n"

/-! ## Kummer extension Q(zeta_p, p-th root of a) -/

def kummerExtensionExample (p a : Nat) : FieldExtension :=
  -- Q(zeta_p, a^(1/p))/Q(zeta_p), cyclic of degree p
  sorry

/-! ## Artin-Schreier extension in characteristic p -/

def artinSchreierExample (p : Nat) (a : Nat) : FieldExtension :=
  -- F_p(t, root of x^p - x - a)/F_p(t), cyclic of degree p
  sorry

/-! ## Symmetric polynomials and discriminant -/

def discriminantExample : String :=
  "For f(x) = x^3 - 3x + 1, discriminant = 81 -> Galois group A_3 (cyclic of order 3)"

def symmetricPolynomialGalois : String :=
  "The splitting field of a polynomial of degree n with symmetric Galois group S_n has no nontrivial intermediate fields"

/-! ## Galois group of x^n - a -/

def galoisGroupOfXnMinusA (n : Nat) (a : Nat) : String :=
  "Gal(Q(zeta_n, a^(1/n))/Q) is a subgroup of the affine group AGL(1, Z/nZ) = (Z/nZ) semidirect (Z/nZ)^x"

/-! ## #eval tests -/

#eval "Examples.Standard: quadraticExtension, biquadraticExtension, cyclotomicExtension"
#eval "Examples.Standard: cubicNonGalois, finiteFieldExtension, kummerExtension"
#eval "Examples.Standard: artinSchreierExample, discriminantExample, galoisOfXnMinusA"
