/-
# MiniFieldTheoryCore.Theorems.UniversalProperties

Universal mapping properties of field constructions: field of fractions,
algebraic closure, separable closure, splitting field, and the compositum
(tensor product) of field extensions.
-/

import MiniFieldTheoryCore.Core.Basic
import MiniFieldTheoryCore.Core.Laws
import MiniFieldTheoryCore.Constructions.Universal
import MiniFieldTheoryCore.Constructions.Products
import MiniFieldTheoryCore.Morphisms.Hom
import MiniFieldTheoryCore.Morphisms.Iso

namespace MiniFieldTheoryCore

/-! ## Universal property of the field of fractions -/

/-- Frac(R) is the universal field containing the integral domain R.
    For any field K and injective homomorphism f: R → K, there exists
    a unique field homomorphism φ: Frac(R) → K extending f. -/
axiom fieldOfFractionsUMP (R : Ring) (hdomain : True) (F : Field) (ι : RingHom R F.ring)
    (K : Field) (f : RingHom R K.ring) (_hinj : True) :
    ∃! (φ : FieldHom F K), True  -- φ ∘ ι = f

/-- The field of fractions is the initial object in the category of
    fields under R. -/
axiom fieldOfFractionsIsInitial (R : Ring) (_hdomain : True) (F : Field) (ι : RingHom R F.ring) : True

/-- Frac(R) is unique up to unique isomorphism: if F and G both satisfy
    the universal property, then F ≅ G uniquely. -/
axiom fieldOfFractionsUniqueUpToUniqueIso (R : Ring) (_hdomain : True)
    (F G : Field) (ιF : RingHom R F.ring) (ιG : RingHom R G.ring)
    (_humpF : True) (_humpG : True) :
    -- ∃! φ : F ≅ G such that
    isIsomorphic F G

/-! ## Universal property of the algebraic closure -/

/-- F^alg is the universal algebraically closed field containing F:
    any field embedding F → L into an algebraically closed field L
    extends to an embedding F^alg → L. -/
axiom algebraicClosureUMP (F : Field) (Falg : Field) (ι : FieldHom F Falg)
    (hAC : isAlgebraicallyClosed Falg)
    (L : Field) (hACL : isAlgebraicallyClosed L) (f : FieldHom F L) :
    -- ∃ φ : Falg → L extending f (i.e., φ ∘ ι = f)
    True

/-- Algebraic closure is unique up to isomorphism, but not unique
    isomorphism (there are many). -/
axiom algebraicClosureIsomorphismNotUnique (F : Field) : String :=
  "Algebraic closures of F are isomorphic as F-algebras, but the
   isomorphism is NOT unique in general. For example, Galois theory
   shows that choices of embeddings correspond to elements of the
   absolute Galois group, which is often nontrivial."

/-- The algebraic closure of the algebraic closure is the original
    algebraic closure (up to isomorphism). -/
axiom algebraicClosureIdempotent (F : Field) (Falg : Field) (hAC : isAlgebraicallyClosed Falg)
    (_halg : True) : isAlgebraicallyClosed Falg

/-! ## Universal property of the separable closure -/

/-- F^sep is the universal separable algebraic extension of F:
    any separable algebraic extension E/F embeds into F^sep. -/
axiom separableClosureUMP (F : Field) (Fsep : Field) (ι : FieldHom F Fsep)
    (hsep : True) (E : FieldExtension) (hsepE : True) (halg : isAlgebraicExtension E)
    (_hbase : isIsomorphic E.baseField F) :
    ∃ (φ : FieldHom E.extensionField Fsep), True  -- φ extends F → F^sep

/-- Every separable algebraic extension of F embeds uniquely into F^sep
    up to automorphism of F^sep over F. -/
axiom separableClosureEmbeddingUniqueUpToGalois (F : Field) : True

/-! ## Universal property of the splitting field -/

/-- The splitting field of a polynomial f over F is the minimal field
    extension E/F such that f splits completely in E[x]. -/
axiom splittingFieldExists (F : Field) (coeffs : List F.ring.carrier) (hnonconst : coeffs.length > 1) :
    ∃ (E : FieldExtension),
      -- f splits in E[x]
      True
      -- and E is generated by the roots of f over F

/-- The splitting field has the universal property: if f splits in any
    extension L/F, then there is an F-embedding of the splitting field
    into L. -/
axiom splittingFieldUMP (F : Field) (coeffs : List F.ring.carrier) (E : FieldExtension)
    (hsplit : True)  -- E is a splitting field of f
    (L : FieldExtension) (hsplitL : True) -- f splits in L
    (_hbase : isIsomorphic L.baseField F) :
    ∃ (φ : FieldHom E.extensionField L.extensionField), True
    -- φ restricts to identity on F

/-- Any two splitting fields of the same polynomial over F are isomorphic
    as F-algebras (not necessarily uniquely). -/
axiom splittingFieldsIsomorphic (F : Field) (coeffs : List F.ring.carrier)
    (E₁ E₂ : FieldExtension) (hsplit₁ : True) (hsplit₂ : True) :
    isIsomorphic E₁.extensionField E₂.extensionField

/-! ## Universal property of the compositum (tensor product) -/

/-- If E and F are extensions of K contained in a common overfield L,
    the compositum EF is the smallest subfield of L containing both
    E and F. -/
axiom compositumUniversal (K E F L : Field) (ιE : FieldHom K E) (ιF : FieldHom K F)
    (ιL : FieldHom E L) (ιL' : FieldHom F L) :
    -- EF ⊆ L is the "join" in the lattice of subfields of L/K
    True

/-- The tensor product E ⊗_K F maps to the compositum EF (when both
    are contained in L). The compositum is the quotient of the tensor
    product by a maximal ideal. -/
axiom compositumAsTensorProduct (K E F : Field) (ιE : FieldHom K E) (ιF : FieldHom K F) :
    -- EF ≅ (E ⊗_K F) / P for some prime ideal P
    True

/-- The compositum of two Galois extensions is Galois. -/
axiom compositumOfGaloisIsGalois (K E F : Field) (hgalE : True) (hgalF : True) : True

/-! ## Universal property: field extension as adjunction -/

/-- Adjoining a root of an irreducible polynomial: F[x]/(f(x)) is a
    field extension of F in which f has a root, and it is the universal
    such extension. -/
axiom adjunctionUMP (F : Field) (f : List F.ring.carrier) (hirred : True) :
    -- F[x]/(f) is a field, and for any K/F with a root of f,
    -- there is a unique F-hom F[x]/(f) → K
    True

/-- Kronecker's construction: for any non-constant polynomial f over F,
    there exists an extension E/F where f has a root. -/
axiom kroneckerConstruction (F : Field) (coeffs : List F.ring.carrier) (hnonconst : coeffs.length > 1) :
    ∃ (E : FieldExtension) (α : E.extensionField.ring.carrier),
      True  -- f(α) = 0 in E

/-! ## #eval examples -/

#eval "Theorems.UniversalProperties: fieldOfFractionsUMP (universal field under R)"
#eval "Theorems.UniversalProperties: fieldOfFractionsIsInitial, unique up to unique iso"
#eval "Theorems.UniversalProperties: algebraicClosureUMP (embeds into any alg-closed)"
#eval "Theorems.UniversalProperties: algebraic closure isomorphism NOT unique"
#eval "Theorems.UniversalProperties: separableClosureUMP (universal separable algebraic)"
#eval "Theorems.UniversalProperties: splittingFieldExists, splittingFieldUMP"
#eval "Theorems.UniversalProperties: splittingFieldsIsomorphic (not uniquely)"
#eval "Theorems.UniversalProperties: compositumUniversal, compositumAsTensorProduct"
#eval "Theorems.UniversalProperties: compositumOfGaloisIsGalois"
#eval "Theorems.UniversalProperties: adjunctionUMP F[x]/(f), kroneckerConstruction"

end MiniFieldTheoryCore
