/-
# MiniAlgebraicStructures.Examples.Counterexamples

Counterexamples in algebraic structures:
A_5 is simple but not solvable.
Non-commutative rings without identity.
Semigroups that are not monoids.
Non-associative algebras (Lie, Jordan).
Varieties not finitely based.
-/

import MiniAlgebraicStructures.Examples.Standard

namespace MiniAlgebraicStructures

/-! ## A_5 is simple but not solvable -/

def a5IsSimple : String :=
  "A_5 is a simple group of order 60 -- the smallest non-abelian simple group"

def a5NotSolvable : String :=
  "A_5 is not solvable, which implies the general quintic is not solvable by radicals"

/-! ## Non-commutative ring without identity -/

def nonCommutativeRingNoIdentity : String :=
  "2Z = {even integers} is a ring without identity; Mat_2(2Z) is non-commutative without identity"

/-! ## Semigroup not a monoid -/

def semigroupNotMonoid : String :=
  "Even positive integers {2, 4, 6, ...} under addition: no identity element (0 is not positive)"

/-! ## Non-associative algebra examples -/

def lieAlgebraExample : String :=
  "R^3 with cross product: a Lie algebra, non-associative because (a x b) x c ≠ a x (b x c) in general"

def jordanAlgebraExample : String :=
  "Symmetric matrices under the Jordan product a o b = (ab + ba)/2"

def octonionAlgebra : String :=
  "Octonions O: the largest normed division algebra, non-associative but alternative"

/-! ## Monoid not embeddable in a group -/

def monoidNotEmbeddableInGroup : String :=
  "The bicyclic monoid: has no group of fractions, showing not every monoid embeds in a group"

/-! ## Idempotent semigroups (bands) -/

def rectangularBand : String :=
  "A rectangular band satisfies xyz = xz; a classic example of an idempotent semigroup"

/-! ## Varieties that are not finitely based -/

def varietyNotFinitelyBased : String :=
  "Lyndon's example: the variety generated by a certain 7-element groupoid is not finitely based"

def perkinsNonfinitelyBasedSemigroup : String :=
  "Perkins' semigroup: a 6-element semigroup generating a non-finitely based variety"

/-! ## Counterexamples to HSP characterizations -/

def pseudoVariety : String :=
  "The class of all finite groups is closed under H, S, P_fin but not arbitrary P; a pseudovariety, not a variety"

def quasivarietyNotVariety : String :=
  "The class of torsion-free groups is a quasivariety (defined by implications) but not a variety"

/-! ## Counterexamples summary -/

def counterexamplesAlgebraicStructures : String :=
  "A_5 simple|2Z rng|even semigroup|Lie/Jordan/Octonion|bicyclic monoid|rectangular band|non-finitely based|pseudovariety|quasivariety"

/-! ## #eval tests -/

#eval "Examples.Counterexamples: a5IsSimple, a5NotSolvable, rng without identity"
#eval "Examples.Counterexamples: semigroupNotMonoid, non-associative algebras"
#eval "Examples.Counterexamples: monoidNotEmbeddable, idempotent bands"
#eval "Examples.Counterexamples: non-finitely based varieties, pseudo/quasi varieties"
#eval s!"Counterexamples: {counterexamplesAlgebraicStructures}"
