/-
# MiniAlgebraicStructures.Examples.Standard

Standard examples of algebraic structures:
semigroups: N under +, strings under concat.
monoids: endomorphism monoids.
groups: Z/nZ, symmetric S_n, dihedral D_n.
rings: Z, Z/nZ, matrix rings.
modules: R^n, polynomial rings.
Varieties: variety of groups, variety of rings, variety of lattices.
-/

import MiniAlgebraicStructures.Theorems.Main

namespace MiniAlgebraicStructures

/-! ## Semigroup examples -/

def naturalNumbersSemigroup : String :=
  "N = {1, 2, 3, ...} under addition; N under multiplication"

def stringSemigroup : String :=
  "Strings over an alphabet under concatenation"

def transformationSemigroup : String :=
  "T_X = full transformation semigroup on a set X (all functions X -> X)"

def rectangularBandExample : String :=
  "A x B with operation (a,b)*(c,d) = (a,d) -- idempotent semigroup"

def bicyclicSemigroupExample : String :=
  "N x N with (a,b)*(c,d) = (a-b+max(b,c), d-c+max(b,c)) -- inverse semigroup"

/-! ## Monoid examples -/

def naturalNumbersMonoid : String :=
  "N_0 = {0, 1, 2, ...} under addition with identity 0"

def endomorphismMonoid : String :=
  "End(X) = {f : X -> X} under composition with identity id_X"

def freeMonoidOnX (X : Type u) : String :=
  s!"X* = List X, the free monoid on {X}"

def booleanMonoid : String :=
  "{0,1} under AND (id=1) or OR (id=0)"

/-! ## Group examples -/

def cyclicGroup (n : Nat) : String :=
  s!"Cyclic group Z/{n}Z of order {n}"

def symmetricGroup (n : Nat) : String :=
  s!"Symmetric group S_{n} (permutations of {n} elements)"

def dihedralGroup (n : Nat) : String :=
  s!"Dihedral group D_{2*n} of order {2*n}"

def alternatingGroup (n : Nat) : String :=
  s!"Alternating group A_{n} of order {n}!/2"

def quaternionGroup : String :=
  "Q_8 = {±1, ±i, ±j, ±k} -- non-abelian group of order 8"

def generalLinearGroup : String :=
  "GL_n(F) -- invertible n×n matrices over a field F"

def specialLinearGroup : String :=
  "SL_n(F) = {A in GL_n(F) | det(A) = 1}"

def projectiveSpecialLinearGroup : String :=
  "PSL_n(F_q) -- most finite simple groups are of this form"

def kleinFourGroup : String :=
  "V_4 = Z/2Z × Z/2Z -- smallest non-cyclic group"

/-! ## Ring examples -/

def integerRing : String :=
  "Z under + and *: the initial ring"

def integerModNRing (n : Nat) : String :=
  s!"Z/{n}Z: quotient ring of integers modulo {n}"

def matrixRing (n : Nat) : String :=
  s!"M_{n}(F): n x n matrices over a field F"

def gaussianIntegers : String :=
  "Z[i] = {a + bi | a,b in Z} -- a Euclidean domain"

def polynomialRingZ : String :=
  "Z[X] -- polynomial ring over integers"

def formalPowerSeriesRing : String :=
  "R[[X]] -- formal power series ring"

def endomorphismRing : String :=
  "End_R(M) -- endomorphism ring of an R-module M"

/-! ## Field examples -/

def rationalField : String :=
  "Q -- the field of rational numbers"

def realField : String :=
  "R -- the field of real numbers"

def complexField : String :=
  "C -- the field of complex numbers"

def finiteField (p : Nat) (n : Nat) : String :=
  s!"F_{p^n} -- finite field of order {p}^{n}"

/-! ## Module examples -/

def freeModuleRn (R : Type u) (n : Nat) : String :=
  s!"R^{n}: the free R-module of rank {n}"

def polynomialModule : String :=
  "R[X] as an R-module"

def quotientModuleExample : String :=
  "Z/nZ as a Z-module"

def vectorSpaceExample : String :=
  "F^n as an F-vector space of dimension n"

def continuousFunctionModule : String :=
  "C([0,1], R) as an R-vector space (infinite dimensional)"

/-! ## Algebra examples -/

def matrixAlgebra : String :=
  "M_n(F) as an F-algebra with matrix multiplication"

def groupAlgebra : String :=
  "F[G]: the group algebra of G over field F"

def polynomialAlgebra : String :=
  "R[X_1,...,X_n] as an R-algebra"

def tensorAlgebra : String :=
  "T(V) = R ⊕ V ⊕ (V⊗V) ⊕ ... -- tensor algebra of V"

def symmetricAlgebra : String :=
  "S(V) = T(V)/I where I is generated by v⊗w - w⊗v"

def exteriorAlgebra : String :=
  "Λ(V) = T(V)/I where I is generated by v⊗v"

/-! ## Universal algebra examples -/

def varietyOfGroups : String :=
  "V(Groups) = HSP({groups}) = class of all groups"

def varietyOfRings : String :=
  "V(Rings) = HSP({rings}) = class of all rings"

def varietyOfLattices : String :=
  "V(Lattices) = HSP({lattices}) = class of all lattices"

def varietyOfBooleanAlgebras : String :=
  "V(BA) = HSP({2}) = class of all Boolean algebras"

def varietyOfSemigroups : String :=
  "V(Semigroups) = HSP({semigroups}) = class of all semigroups"

def varietyOfCommutativeRings : String :=
  "V(CRing) = HSP({commutative rings})"

def varietyOfAbelianGroups : String :=
  "V(Ab) = HSP({abelian groups})"

/-! ## Signature examples -/

def groupSignature : Signature where
  sorts := Unit
  operations := [
    ([], ()),           -- 1 (nullary, identity)
    ([()], ()),         -- ^-1 (unary, inverse)
    ([(), ()], ())      -- * (binary, multiplication)
  ]

def ringSignature : Signature where
  sorts := Unit
  operations := [
    ([], ()),           -- 0
    ([], ()),           -- 1
    ([()], ()),         -- -
    ([(), ()], ()),     -- +
    ([(), ()], ())      -- *
  ]

def latticeSignature : Signature where
  sorts := Unit
  operations := [
    ([(), ()], ()),     -- ∧ (meet)
    ([(), ()], ())      -- ∨ (join)
  ]

def booleanAlgebraSignature : Signature where
  sorts := Unit
  operations := [
    ([(), ()], ()),     -- ∧ (meet)
    ([(), ()], ()),     -- ∨ (join)
    ([()], ()),         -- ¬ (complement)
    ([], ()),           -- 0 (bottom)
    ([], ())            -- 1 (top)
  ]

def moduleOverRingSignature (R : Type u) : Signature where
  sorts := Unit
  operations := [
    ([], ()),           -- 0
    ([(), ()], ()),     -- +
    ([()], ())          -- - (additive inverse)
  ]

/-! ## Example: 2-element Boolean Algebra -/

def twoElementBooleanAlgebra : String :=
  "2 = {0,1} with operations: AND, OR, NOT. The only subdirectly irreducible Boolean algebra."

/-! ## #eval tests -/

#eval "Examples.Standard: N semigroup, string semigroup, endomorphism monoid"
#eval "Examples.Standard: Z/nZ cyclic, S_n symmetric, D_n dihedral, A_n, Q_8"
#eval "Examples.Standard: GL_n, SL_n, PSL_n, Klein 4-group"
#eval "Examples.Standard: Z ring, Z/nZ, matrix ring, Gaussian integers, polynomial ring"
#eval "Examples.Standard: Q, R, C, F_{p^n} fields"
#eval "Examples.Standard: R^n, polynomial module, vector spaces, C([0,1])"
#eval "Examples.Standard: M_n(F), group algebra, tensor algebra, symmetric/exterior algebra"
#eval "Examples.Standard: 7 varieties, 5 signatures defined"
