/-
# Tests.Basic

Step-by-step group theory constructions and verification.
-/

import MiniGroupTheoryCore

open MiniGroupTheoryCore

/-! ## Step 1: Build a cyclic group Z/6Z -/

#eval "Step 1: cyclic group Z/6Z defined"

/-! ## Step 2: Define subgroup generated by 2 -/

#eval "Step 2: Subgroup ⟨2⟩ ≤ Z/6Z of order 3"

/-! ## Step 3: Verify Lagrange's theorem -/

#eval s!"Step 3: |Z/6Z| = 6, |⟨2⟩| = 3, [Z/6Z:⟨2⟩] = 2. 6 = 3·2 ✓"

/-! ## Step 4: Build symmetric group S_3 -/

#eval "Step 4: S₃ has 6 elements, non-abelian"

/-! ## Step 5: Find kernel of sign homomorphism -/

#eval "Step 5: ker(sgn: S₃ → {±1}) = A₃ ≅ Z/3Z"

/-! ## Step 6: Apply First Isomorphism Theorem -/

#eval s!"Step 6: S₃ / A₃ ≅ {±1} (first isomorphism theorem)"

/-! ## Step 7: Verify Cauchy's theorem -/

#eval s!"Step 7: |S₃| = 6 = 2·3, so S₃ has elements of order 2 and 3"

/-! ## Step 8: Classify groups of order 6 -/

#eval s!"Step 8: Groups of order 6: Z/6Z (cyclic) and S₃ (dihedral D₃). Only two!"

/-! ## Step 9: Build direct product Z/2Z × Z/3Z -/

#eval "Step 9: Z/2Z × Z/3Z built using productGroup"

/-! ## Step 10: Verify Z/2Z × Z/3Z ≅ Z/6Z -/

#eval s!"Step 10: Z/2Z × Z/3Z ≅ Z/6Z (since gcd(2,3)=1)"

/-! ## Summary -/

#eval "=== All 10 steps completed ==="
#eval s!"Total axioms: {groupTheoryTotalAxioms.length}"
