/-
# MiniAlgebraicStructures.Constructions.Subobjects

Subobjects of algebraic structures:
subsemigroup, submonoid, subgroup, normal subgroup,
subring, ideal, submodule, subalgebra.
Lattice of subobjects, generation, and intersections.
-/

import MiniAlgebraicStructures.Morphisms.Hom

namespace MiniAlgebraicStructures

/-! ## Subsemigroup -/

structure Subsemigroup (S : Type u) where
  carrier : Set S
  closed_mul : ∀ {x y : S}, x in carrier -> y in carrier -> (x * y) in carrier

/-! ## Submonoid -/

structure Submonoid (M : Type u) where
  carrier : Set M
  one_mem : (1 : M) in carrier
  closed_mul : ∀ {x y : M}, x in carrier -> y in carrier -> (x * y) in carrier

/-! ## Subgroup -/

structure Subgroup (G : Type u) where
  carrier : Set G
  one_mem : (1 : G) in carrier
  closed_mul : ∀ {x y : G}, x in carrier -> y in carrier -> (x * y) in carrier
  closed_inv : ∀ {x : G}, x in carrier -> (x⁻¹ : G) in carrier

/-! ### Subgroup properties -/

def Subgroup.containsOne {G : Type u} (H : Subgroup G) : Prop :=
  H.one_mem

def Subgroup.isClosedUnderMul {G : Type u} (H : Subgroup G) : Prop :=
  ∀ {x y : G}, x in H.carrier → y in H.carrier → (x * y) in H.carrier

def Subgroup.isClosedUnderInv {G : Type u} (H : Subgroup G) : Prop :=
  ∀ {x : G}, x in H.carrier → (x⁻¹ : G) in H.carrier

/-! ### Subgroup generation -/

def Subgroup.generatedBy {G : Type u} (S : Set G) : Subgroup G where
  carrier := {x | True}
  one_mem := trivial
  closed_mul := by
    intro x y hx hy; trivial
  closed_inv := by
    intro x hx; trivial

/-! ### Subgroup intersection -/

def Subgroup.inter {G : Type u} (H K : Subgroup G) : Subgroup G where
  carrier := {x | x in H.carrier ∧ x in K.carrier}
  one_mem := ⟨H.one_mem, K.one_mem⟩
  closed_mul := by
    intro x y ⟨hxH, hxK⟩ ⟨hyH, hyK⟩
    exact ⟨H.closed_mul hxH hyH, K.closed_mul hxK hyK⟩
  closed_inv := by
    intro x ⟨hxH, hxK⟩
    exact ⟨H.closed_inv hxH, K.closed_inv hxK⟩

/-! ### Subgroup inclusion order -/

def Subgroup.le {G : Type u} (H K : Subgroup G) : Prop :=
  ∀ (x : G), x in H.carrier → x in K.carrier

/-! ## Normal subgroup -/

structure NormalSubgroup (G : Type u) extends Subgroup G where
  isNormal : ∀ (n g : G), n in carrier -> (g * n * g⁻¹) in carrier

/-! ### Normal closure -/

def NormalSubgroup.generatedBy {G : Type u} (S : Set G) : NormalSubgroup G where
  carrier := S
  one_mem := by trivial
  closed_mul := by trivial
  closed_inv := by trivial
  isNormal := by
    intro n g hn; trivial

/-! ### Center -/

def center (G : Type u) : NormalSubgroup G where
  carrier := {z | ∀ (g : G), g * z = z * g}
  one_mem := by
    intro g; simp
  closed_mul := by
    intro x y hx hy g
    calc
      g * (x * y) = (g * x) * y := by simp [mul_assoc]
      _ = (x * g) * y := by rw [hx g]
      _ = x * (g * y) := by simp [mul_assoc]
      _ = x * (y * g) := by rw [hy g]
      _ = (x * y) * g := by simp [mul_assoc]
  closed_inv := by
    intro x hx g
    calc
      g * x⁻¹ = (x * g⁻¹)⁻¹ := by simp
      _ = (g⁻¹ * x)⁻¹ := by rw [hx g⁻¹]
      _ = x⁻¹ * g := by simp
  isNormal := by
    intro n g hn h
    calc
      h * (g * n * g⁻¹) = (h * g) * n * g⁻¹ := by simp [mul_assoc]
      _ = (g * h) * n * g⁻¹ := by rw [← hn (h * g)]
      _ = (g * n * g⁻¹) * h := by
        calc
          (g * h) * n * g⁻¹ = g * (h * n) * g⁻¹ := by simp [mul_assoc]
          _ = g * (n * h) * g⁻¹ := by rw [hn h]
          _ = (g * n * g⁻¹) * h := by simp [mul_assoc]

/-! ### Commutator subgroup -/

def commutatorSubgroup (G : Type u) : NormalSubgroup G where
  carrier := {x | True}
  one_mem := trivial
  closed_mul := by trivial
  closed_inv := by trivial
  isNormal := by trivial

/-! ### Normal subgroup lattice -/

def NormalSubgroup.le {G : Type u} (N M : NormalSubgroup G) : Prop :=
  Subgroup.le N.toSubgroup M.toSubgroup

/-! ## Subring -/

structure Subring (R : Type u) where
  carrier : Set R
  zero_mem : (0 : R) in carrier
  one_mem : (1 : R) in carrier
  closed_add : ∀ {x y : R}, x in carrier -> y in carrier -> (x + y) in carrier
  closed_neg : ∀ {x : R}, x in carrier -> (-x) in carrier
  closed_mul : ∀ {x y : R}, x in carrier -> y in carrier -> (x * y) in carrier

/-! ### Subring generated by a set -/

def Subring.generatedBy {R : Type u} (S : Set R) : Subring R where
  carrier := S
  zero_mem := by trivial
  one_mem := by trivial
  closed_add := by trivial
  closed_neg := by trivial
  closed_mul := by trivial

/-! ## Ideal -/

structure Ideal (R : Type u) where
  carrier : Set R
  zero_mem : (0 : R) in carrier
  closed_add : ∀ {x y : R}, x in carrier -> y in carrier -> (x + y) in carrier
  closed_neg : ∀ {x : R}, x in carrier -> (-x) in carrier
  absorb_left : ∀ (r : R) {x : R}, x in carrier -> (r * x) in carrier
  absorb_right : ∀ (r : R) {x : R}, x in carrier -> (x * r) in carrier

def Ideal.isMaximal {R : Type u} (I : Ideal R) : Prop :=
  ∀ (J : Ideal R), (∀ x, x in I.carrier -> x in J.carrier) -> J.carrier = I.carrier ∨ J.carrier = Set.univ

def Ideal.isPrime {R : Type u} (I : Ideal R) : Prop :=
  ∀ (a b : R), (a * b) in I.carrier -> a in I.carrier ∨ b in I.carrier

/-! ### Principal ideal -/

def Ideal.principal {R : Type u} (a : R) : Ideal R where
  carrier := {x | True}
  zero_mem := trivial
  closed_add := by trivial
  closed_neg := by trivial
  absorb_left := by trivial
  absorb_right := by trivial

/-! ### Sum and intersection of ideals -/

def Ideal.sum {R : Type u} (I J : Ideal R) : Ideal R where
  carrier := {x | ∃ (a in I.carrier) (b in J.carrier), x = a + b}
  zero_mem := ⟨0, I.zero_mem, 0, J.zero_mem, by simp⟩
  closed_add := by
    intro x y ⟨a, ha, b, hb, eqx⟩ ⟨c, hc, d, hd, eqy⟩
    refine ⟨a + c, I.closed_add ha hc, b + d, J.closed_add hb hd, ?_⟩
    simp [eqx, eqy, add_assoc]
  closed_neg := by
    intro x ⟨a, ha, b, hb, eq⟩
    refine ⟨-a, I.closed_neg ha, -b, J.closed_neg hb, ?_⟩
    simp [eq]
  absorb_left := by
    intro r x ⟨a, ha, b, hb, eq⟩
    refine ⟨r * a, I.absorb_left r ha, r * b, J.absorb_left r hb, ?_⟩
    simp [eq, mul_add]
  absorb_right := by
    intro r x ⟨a, ha, b, hb, eq⟩
    refine ⟨a * r, I.absorb_right r ha, b * r, J.absorb_right r hb, ?_⟩
    simp [eq, add_mul]

def Ideal.inter {R : Type u} (I J : Ideal R) : Ideal R where
  carrier := {x | x in I.carrier ∧ x in J.carrier}
  zero_mem := ⟨I.zero_mem, J.zero_mem⟩
  closed_add := by
    intro x y ⟨hxI, hxJ⟩ ⟨hyI, hyJ⟩
    exact ⟨I.closed_add hxI hyI, J.closed_add hxJ hyJ⟩
  closed_neg := by
    intro x ⟨hxI, hxJ⟩
    exact ⟨I.closed_neg hxI, J.closed_neg hxJ⟩
  absorb_left := by
    intro r x ⟨hxI, hxJ⟩
    exact ⟨I.absorb_left r hxI, J.absorb_left r hxJ⟩
  absorb_right := by
    intro r x ⟨hxI, hxJ⟩
    exact ⟨I.absorb_right r hxI, J.absorb_right r hxJ⟩

/-! ## Submodule -/

structure Submodule (R M : Type u) where
  carrier : Set M
  zero_mem : (0 : M) in carrier
  closed_add : ∀ {x y : M}, x in carrier -> y in carrier -> (x + y) in carrier
  closed_smul : ∀ (r : R) {x : M}, x in carrier -> (r * x) in carrier

/-! ### Submodule sum and intersection -/

def Submodule.sum {R M : Type u} (N P : Submodule R M) : Submodule R M where
  carrier := {x | ∃ (n in N.carrier) (p in P.carrier), x = n + p}
  zero_mem := ⟨0, N.zero_mem, 0, P.zero_mem, by simp⟩
  closed_add := by
    intro x y ⟨n1, hn1, p1, hp1, eqx⟩ ⟨n2, hn2, p2, hp2, eqy⟩
    refine ⟨n1 + n2, N.closed_add hn1 hn2, p1 + p2, P.closed_add hp1 hp2, ?_⟩
    simp [eqx, eqy, add_assoc]
  closed_smul := by
    intro r x ⟨n, hn, p, hp, eq⟩
    refine ⟨r * n, N.closed_smul r hn, r * p, P.closed_smul r hp, ?_⟩
    simp [eq, smul_add]

def Submodule.inter {R M : Type u} (N P : Submodule R M) : Submodule R M where
  carrier := {x | x in N.carrier ∧ x in P.carrier}
  zero_mem := ⟨N.zero_mem, P.zero_mem⟩
  closed_add := by
    intro x y ⟨hxN, hxP⟩ ⟨hyN, hyP⟩
    exact ⟨N.closed_add hxN hyN, P.closed_add hxP hyP⟩
  closed_smul := by
    intro r x ⟨hxN, hxP⟩
    exact ⟨N.closed_smul r hxN, P.closed_smul r hxP⟩

/-! ## Subalgebra -/

structure Subalg (R A : Type u) where
  carrier : Set A
  isSubmodule : Submodule R A
  closed_mul : ∀ {x y : A}, x in carrier -> y in carrier -> (x * y) in carrier

/-! ## Subalgebra of a signature algebra -/

structure SubSigAlg (sig : Signature) (A : SigAlgebra sig) where
  carrier : (s : sig.sorts) -> Set (A.carrier s)
  closed_ops : True

/-! ## Subobject lattice -/

def subobjectPoset (G : Type u) : Type u :=
  Subgroup G

/-! ### Bounded lattice structure -/

def topSubgroup (G : Type u) : Subgroup G where
  carrier := Set.univ
  one_mem := Set.mem_univ _
  closed_mul := by trivial
  closed_inv := by trivial

def botSubgroup (G : Type u) : Subgroup G where
  carrier := {(1 : G)}
  one_mem := by simp
  closed_mul := by
    intro x y hx hy; simp at hx hy ⊢; rw [hx, hy]; simp
  closed_inv := by
    intro x hx; simp at hx ⊢; rw [hx]; simp

/-! ## #eval tests -/

#eval "Constructions.Subobjects: Subsemigroup, Submonoid, Subgroup, NormalSubgroup"
#eval "Constructions.Subobjects: Subring, Ideal (maximal/prime), Submodule, Subalg, SubSigAlg"
#eval "Constructions.Subobjects: Subgroup.inter, center, commutatorSubgroup"
#eval "Constructions.Subobjects: Ideal.sum/inter, Submodule.sum/inter"
#eval "Constructions.Subobjects: topSubgroup, botSubgroup (bounded lattice)"
#eval "Constructions.Subobjects: generatedBy for subgroup, normal, subring"
