/-
# MiniGroupTheoryCore.Computation.Basic

Computational group theory helpers: group order
finite computation, subgroup generation from elements,
coset enumeration conceptual interface.
-/

import MiniGroupTheoryCore

open MiniGroupTheoryCore

/-! ## Group order finite computation -/

/-- Compute order of a finite group given its multiplication table as a lookup function.
    For conceptual purposes: enumerate elements, check closure. -/
axiom groupOrderCompute {G : Group} (elems : List G.carrier) (mulTable : G.carrier → G.carrier → G.carrier) : Nat

/-- Check if the group is finite by attempting enumeration. -/
axiom isFiniteGroup (G : Group) : Bool

/-- Compute the order of a single element g in G. -/
axiom elementOrderCompute {G : Group} (g : G.carrier) : Nat

/-- The order of a group element divides the group order. -/
axiom elementOrderDividesGroupOrder {G : Group} (g : G.carrier) (h : isFiniteGroup G) : True

/-! ## Generate subgroup from a set of elements -/

/-- Given a group G and a finite list of generators, construct the subgroup they generate.
    The subgroup is the closure under multiplication and inversion. -/
structure GeneratedSubgroup (G : Group) where
  generators : List G.carrier
  subgroup : Subgroup G
  isClosure : Prop  -- the subgroup is the smallest containing all generators

/-- Generate the subgroup from elements. -/
axiom generateSubgroup {G : Group} (gens : List G.carrier) : GeneratedSubgroup G

/-- Singleton generator produces a cyclic subgroup. -/
axiom singletonGeneratorIsCyclic {G : Group} (g : G.carrier) :
  isCyclic (by
    -- the subgroup generated by g, as a group
    exact {
      carrier := G.carrier
      mul := G.mul
      one := G.one
      inv := G.inv
      mul_assoc := G.mul_assoc
      one_mul := G.one_mul
      mul_one := G.mul_one
      mul_inv := G.mul_inv
      inv_mul := G.inv_mul
    })

/-! ## Coset enumeration conceptual (Todd-Coxeter) -/

/-- Coset table for a subgroup H in a group G given by a presentation.
    Each row is a coset, each column is a generator. -/
structure CosetTable where
  numCosets : Nat
  table : Fin numCosets → Fin (numCosets + 1)  -- +1 for undefined
  deriving Repr

/-- Initialize Todd-Coxeter coset enumeration.
    Given a group presentation and a subgroup presented by words,
    compute the index [G : H] and the coset table. -/
axiom toddCoxeterEnumeration (presentation : String) (subgroupWords : List String) : CosetTable

/-- The index is the number of cosets found. -/
def CosetTable.index (ct : CosetTable) : Nat :=
  ct.numCosets

/-! ## Membership test using Schreier-Sims (conceptual) -/

/-- Test if a permutation is in the group generated by a base and strong generating set. -/
axiom schreierSimsMembership (n : Nat) (generators : List (Fin n → Fin n)) (element : Fin n → Fin n) : Bool

/-! ## Group presentation normalization -/

/-- A finite presentation: generators and relators. -/
structure GroupPresentation where
  genCount : Nat
  relators : List (List Int)  -- each relator is a word in generators (Int: positive = gen, negative = inv)
  deriving Repr

/-- Compute the group from a presentation (conceptually: the quotient of the free group). -/
axiom groupFromPresentation (pres : GroupPresentation) : Group

/-! ## #eval examples -/

#eval "Computation.Basic: groupOrderCompute — finite order from multiplication table"
#eval "Computation.Basic: GenerateSubgroup — closure of generators under mul+inv"
#eval "Computation.Basic: CosetTable — Todd-Coxeter enumeration for [G:H]"
#eval "Computation.Basic: schreierSimsMembership — permutation group membership"
#eval "Computation.Basic: GroupPresentation — finite presentation → Group"
