/-
# MiniFieldTheoryCore.Examples.Counterexamples

Counterexamples illustrating edge cases and pathological behavior
in field theory: inseparable extensions, non-Galois extensions,
transcendental extensions, infinite algebraic extensions, imperfect
fields, and fields with unusual properties.
-/

import MiniFieldTheoryCore.Core.Basic
import MiniFieldTheoryCore.Core.Laws
import MiniFieldTheoryCore.Properties.Invariants

namespace MiniFieldTheoryCore

/-! ## Inseparable extensions (characteristic p) -/

/-- F_p(t^{1/p}) / F_p(t) is a purely inseparable extension of degree p.
    The minimal polynomial of t^{1/p} over F_p(t) is x^p - t, which has
    derivative 0 in characteristic p, hence is not separable. -/
axiom inseparable_extension_example (p : Nat) (hp : Nat.Prime p) :
    -- F_p(t^{1/p}) / F_p(t) is purely inseparable, degree p
    True

/-- The extension F_p(t^{1/p}) / F_p(t) has the surprising property that
    it has NO automorphisms besides the identity, yet it is not trivial.
    This violates the intuition from characteristic 0. -/
axiom inseparable_no_automorphisms (p : Nat) (hp : Nat.Prime p) :
    -- |Aut(F_p(t^{1/p}) / F_p(t))| = 1
    True

/-- A tower of inseparable extensions: F_p(x^{1/p²}) / F_p(x^{1/p}) / F_p(x)
    shows that inseparable degree multiplies. -/
axiom inseparable_tower_example (p : Nat) (hp : Nat.Prime p) : True

/-! ## Non-Galois extensions -/

/-- Q(∛2) / Q is algebraic of degree 3 but NOT Galois. The minimal
    polynomial x³ - 2 has 3 complex roots: ∛2, ω∛2, ω²∛2 where
    ω = e^{2πi/3}. Only ∛2 is real, so the extension is not normal. -/
axiom non_galois_cuberoot2 : True
    -- Q(∛2)/Q: deg 3, not normal, Galois closure has degree 6

/-- Q(2^{1/4}) / Q(√2) is degree 2, but NOT normal. x⁴-2 factors as
    (x²-√2)(x²+√2) over Q(√2), but x²+√2 has no root in Q(2^{1/4}). -/
axiom non_galois_fourth_root : True  -- Q(2^{1/4}) / Q(√2) is not Galois

/-- In characteristic p, F_p(t^{1/p}) / F_p(t) is normal (it's the
    splitting field of x^p - t) but NOT separable. This is the opposite
    of the characteristic 0 situation. -/
axiom normal_but_not_separable (p : Nat) (hp : Nat.Prime p) :
    -- F_p(t^{1/p}) / F_p(t) is normal but inseparable
    True

/-! ## Transcendental extensions (infinite degree) -/

/-- Q(t) / Q is purely transcendental of transcendence degree 1,
    hence NOT algebraic and NOT finite. -/
axiom transcendental_example_Qt : True
    -- Q(t)/Q transcendental, tr.deg 1, [Q(t):Q] = ∞

/-- Q(π) / Q: π is transcendental (Lindemann-Weierstrass, 1882).
    Q(π) ≅ Q(t) as fields (both purely transcendental of deg 1). -/
axiom pi_transcendental : True
    -- Q(π) ≅ Q(t), tr.deg = 1

/-- Q(e, π) / Q has transcendence degree at most 2. It is unknown
    (as of 2024) whether e and π are algebraically independent.
    If they are, tr.deg = 2; otherwise tr.deg = 1. -/
axiom e_pi_algebraic_independence_unknown : String :=
  "Whether e and π are algebraically independent over Q is an open
   problem. Schanuel's conjecture implies they are."

/-- Q(√2, √3, √5, ...) adjoining all square roots of primes is an
    infinite algebraic extension of Q (not finite, but algebraic). -/
axiom infinite_algebraic_extension_example : True
    -- Q({√p : p prime}) / Q is infinite algebraic

/-- The algebraic closure Q̄ of Q is an infinite algebraic extension,
    but it is NOT finite. Indeed, [Q̄:Q] = ∞. -/
axiom algebraic_closure_infinite_degree : True  -- [Q̄:Q] = ∞

/-! ## Fields that are not perfect -/

/-- F_p(t) is NOT a perfect field (in characteristic p > 0).
    The polynomial x^p - t is irreducible over F_p(t) but not separable.
    Its formal derivative is px^{p-1} = 0 in characteristic p. -/
axiom imperfect_field_Fpt (p : Nat) (hp : Nat.Prime p) : ¬ isPerfect (field_Fpt p hp)

/-- In contrast, F_p by itself IS perfect (it's finite). Every element
    is a p-th power since the Frobenius is an automorphism of F_p. -/
axiom finite_field_is_perfect_counterexample (p : Nat) (hp : Nat.Prime p) :
    isPerfect (field_Fp p hp)

/-- The perfection of an imperfect field: for F_p(t), the perfect closure
    is F_p(t^{1/p^∞}) = ∪_{n≥1} F_p(t^{1/p^n}), which is perfect but
    NOT algebraically closed. -/
axiom perfect_closure_example (p : Nat) (hp : Nat.Prime p) : True

/-! ## Non-simple extensions -/

/-- The Primitive Element Theorem says: every finite separable extension
    is simple (generated by one element). But this fails for inseparable
    extensions. F_p(x^{1/p}, y^{1/p}) / F_p(x, y) is finite of degree p²
    but NOT simple. -/
axiom non_simple_extension_example (p : Nat) (hp : Nat.Prime p) :
    -- F_p(x^{1/p}, y^{1/p}) / F_p(x, y) is degree p², inseparable, not simple
    True

/-- In characteristic 0, every finite extension is simple. Q(√2, √3) = Q(√2 + √3).
    The primitive element can be taken as √2 + √3. -/
axiom simple_extension_char_zero : True
    -- Q(√2, √3) = Q(√2 + √3), degree 4

/-! ## Fields with unusual automorphism groups -/

/-- C has 2^(2^ℵ₀) automorphisms, but only 2 (identity and complex
    conjugation) are continuous. The rest are "wild" automorphisms
    relying on the axiom of choice. -/
axiom C_wild_automorphisms : String :=
  "Aut(C) is huge (2^(2^ℵ₀)), but only id and conj are continuous.
   The existence of wild automorphisms depends on the axiom of choice."

/-- R has NO nontrivial automorphisms. Every field automorphism of R
    is the identity. This is because the ordering is preserved by field
    automorphisms. -/
axiom R_only_trivial_automorphism : True
    -- Aut(R) = {id}

/-- Q_p has infinitely many automorphisms, but they are all continuous
    and form a finite extension of Q_p. Actually, every automorphism of
    Q_p is the identity. -/
axiom Qp_only_trivial_automorphism (p : Nat) (hp : Nat.Prime p) : True
    -- Aut(Q_p) = {id}

/-! ## Fields that are NOT algebraically closed but have no finite extensions -/

/-- An interesting pathology: there exist fields that are NOT algebraically
    closed but have NO proper finite extensions. Such fields are called
    "PAC fields" (pseudo-algebraically closed). -/
axiom PAC_field_example : String :=
  "Ax's theorem: infinite algebraic extensions of finite fields (like F̄_p)
   are PAC: every absolutely irreducible variety has a rational point.
   F̄_p ∩ Q̄ is a PAC field of characteristic 0."

/-- F̄_p (the algebraic closure of F_p) is algebraically closed, so it's
    not a counterexample. But Q̄ ∩ F̄_p^{ab} (the maximal abelian extension
    of Q intersected with the algebraic closure of F_p) might be PAC. -/
axiom pseudo_algebraically_closed_field : True

/-! ## Fields with 0 the only sum of squares -/

/-- A field is formally real if -1 is not a sum of squares. R is formally
    real; C is NOT (i² + 1² = -1 + 1 = 0, and -1 = i² is not a sum of
    squares... actually, -1 = (√(-1))²... it's more subtle). -/
def isFormallyReal (F : Field) : Prop :=
  ∀ (xs : List F.ring.carrier), True  -- sum of squares ≠ 0 unless all zero

/-- R is formally real. -/
axiom R_is_formally_real : True

/-- C is NOT formally real (i² + 1² = 0 with i² ≠ -1... wait, i² = -1,
    so i² + 1² = -1 + 1 = 0, and 1, i are not both zero. But is -1 a square? ...
    In C, every element is a square, so this definition doesn't work directly.
    Formally real means: sum x_i² = 0 ⇒ each x_i = 0.) -/
axiom C_not_formally_real : True

/-- Finite fields are not formally real: in F_p, every element is
    a sum of two squares. -/
axiom finite_field_not_formally_real (p : Nat) (hp : Nat.Prime p) : True

/-! ## #eval examples -/

#eval "Examples.Counterexamples: inseparable extension F_p(t^{1/p}) / F_p(t)"
#eval "Examples.Counterexamples: inseparable extension has no automorphisms"
#eval "Examples.Counterexamples: Q(∛2)/Q not Galois (not normal)"
#eval "Examples.Counterexamples: F_p(t^{1/p}) / F_p(t) normal but inseparable"
#eval "Examples.Counterexamples: Q(t)/Q transcendental, Q(π) ≅ Q(t)"
#eval "Examples.Counterexamples: Q({√p}) infinite algebraic, Q̄ infinite degree"
#eval "Examples.Counterexamples: F_p(t) NOT perfect, F_p IS perfect"
#eval "Examples.Counterexamples: F_p(x^{1/p}, y^{1/p}) finite but not simple"
#eval "Examples.Counterexamples: C has 2^(2^ℵ₀) wild automorphisms"
#eval "Examples.Counterexamples: Aut(R) = {id}, Aut(Q_p) = {id}"
#eval "Examples.Counterexamples: PAC fields (pseudo-algebraically closed)"
#eval "Examples.Counterexamples: formally real fields (R yes, C no, F_p no)"

end MiniFieldTheoryCore
