/-
# MiniFieldTheoryCore.Examples.Standard

Standard examples of fields with various characteristics and properties:
Q, R, C, finite fields F_p and F_{p^n}, function fields, and p-adic fields.
Each example demonstrates specific field-theoretic features.
-/

import MiniFieldTheoryCore.Core.Basic
import MiniFieldTheoryCore.Core.Laws
import MiniFieldTheoryCore.Properties.ClassificationData

namespace MiniFieldTheoryCore

/-! ## Rational numbers Q — characteristic 0 prime field -/

/-- Q is the prime field of characteristic 0. Every field of characteristic 0
    contains a unique copy of Q as its prime subfield. -/
axiom field_Q : Field
axiom char_Q : characteristic field_Q = 0

/-- Q is the field of fractions of Z. -/
axiom Q_is_frac_Z : True  -- Q ≅ Frac(Z)

/-- Q has no proper subfields (it is a prime field). -/
axiom Q_is_prime_field : True

/-- Q is NOT algebraically closed: x² - 2 has no root in Q. -/
axiom Q_not_algebraically_closed : ¬ isAlgebraicallyClosed field_Q

/-- The algebraic closure of Q (field of algebraic numbers Q̄) is countable. -/
axiom algebraic_numbers_countable : True  -- Q̄ is countable

/-! ## Real numbers R — real closed field, char 0 -/

/-- R is a real closed field of characteristic 0. It is the unique
    (up to isomorphism) complete ordered field. -/
axiom field_R : Field
axiom char_R : characteristic field_R = 0
axiom R_real_closed : True  -- R is real closed

/-- R is not algebraically closed: x² + 1 has no root in R. -/
axiom R_not_algebraically_closed : ¬ isAlgebraicallyClosed field_R

/-- R[i] ≅ C is algebraically closed (Fundamental Theorem of Algebra). -/
axiom R_adjoin_i_is_C : True  -- R(i) ≅ C

/-! ## Complex numbers C — algebraically closed, char 0 -/

/-- C is the algebraic closure of R and is algebraically closed.
    Characteristic 0, uncountable, and unique up to isomorphism. -/
axiom field_C : Field
axiom char_C : characteristic field_C = 0
axiom C_algebraically_closed : isAlgebraicallyClosed field_C

/-- Fundamental Theorem of Algebra: C is algebraically closed,
    so every non-constant polynomial over C has a root in C. -/
axiom fundamental_theorem_of_algebra : String :=
  "Every non-constant polynomial with complex coefficients has a
   complex root. Equivalently, C is algebraically closed."

/-- C is the splitting field of x² + 1 over R. -/
axiom C_is_R_adjoin_i : True  -- C ≅ R[x]/(x² + 1)

/-- C is isomorphic to the algebraic closure of Q({X_i : i ∈ R}). -/
axiom C_algebraic_closure_of_transcendental_extension : True

/-- C is not finite (uncountable). -/
axiom C_uncountable : True  -- |C| = 𝔠 (continuum)

/-! ## Finite fields F_p — prime fields of characteristic p -/

/-- F_p = Z/pZ is the finite field of prime order p. -/
axiom field_Fp (p : Nat) (hp : Nat.Prime p) : Field
axiom char_Fp (p : Nat) (hp : Nat.Prime p) : characteristic (field_Fp p hp) = p

/-- F_p has exactly p elements. -/
axiom Fp_order (p : Nat) (hp : Nat.Prime p) : True  -- |F_p| = p

/-- F_p is the prime field of characteristic p. Every field of
    characteristic p contains a unique copy of F_p. -/
axiom Fp_is_prime_field (p : Nat) (hp : Nat.Prime p) : True

/-- F_p* ≅ Z/(p-1)Z is cyclic of order p-1. -/
axiom Fp_mult_group_cyclic (p : Nat) (hp : Nat.Prime p) : True  -- F_p* is cyclic

/-- Fermat's Little Theorem over F_p: a^p ≡ a (mod p) for all a ∈ F_p. -/
axiom fermats_little_theorem_field (p : Nat) (hp : Nat.Prime p) : True
    -- a^p = a for all a in F_p (as elements, not as the formal identity)

/-! ## Finite fields F_{p^n} — prime power order -/

/-- GF(pⁿ) for n > 1: a proper extension of F_p. Example: F_4 has 4 elements:
    {0, 1, α, α+1} where α² = α + 1 (characteristic 2). -/
axiom field_Fpn (p n : Nat) (hp : Nat.Prime p) (hn : n > 0) : Field
axiom char_Fpn (p n : Nat) (hp : Nat.Prime p) (hn : n > 0) :
    characteristic (field_Fpn p n hp hn) = p

/-- F_{p^n} / F_p is a Galois extension of degree n, with cyclic Galois
    group generated by the Frobenius x ↦ xᵖ. -/
axiom Fpn_over_Fp_galois (p n : Nat) (hp : Nat.Prime p) (hn : n > 0) : True

/-- Specific example: F_4 = GF(2²) = {0, 1, α, α²} where α² + α + 1 = 0. -/
axiom F4_example : True
    -- F_4 = F_2[α] where α² + α + 1 = 0

/-- F_8 = GF(2³) has 8 elements, constructed using irreducible cubic
    x³ + x + 1 over F_2. -/
axiom F8_example : True
    -- F_8 = F_2[α] where α³ + α + 1 = 0

/-- F_9 = GF(3²) has 9 elements, constructed using irreducible quadratic
    x² + 1 over F_3 (or x² + x - 1). -/
axiom F9_example : True
    -- F_9 = F_3[i] where i² = -1 = 2 (in F_3)

/-! ## Rational function field Q(t) — characteristic 0, transcendence degree 1 -/

/-- Q(t) = field of rational functions in one variable over Q.
    Characteristic 0, transcendence degree 1 over Q. -/
axiom field_Qt : Field
axiom char_Qt : characteristic field_Qt = 0

/-- Q(t) is NOT algebraically closed. For example, x² - t has no root
    in Q(t) (since sqrt(t) is not a rational function). -/
axiom Qt_not_algebraically_closed : ¬ isAlgebraicallyClosed field_Qt

/-- Q(t) / Q is purely transcendental of transcendence degree 1. -/
axiom Qt_purely_transcendental : True

/-- The algebraic closure of Q(t) is enormous: it contains √t, t^{1/n}
    for all n, and much more. -/
axiom Qt_algebraic_closure : True

/-! ## Rational function field F_p(t) — characteristic p, transcendence degree 1 -/

/-- F_p(t) = field of rational functions in one variable over F_p.
    Characteristic p, transcendence degree 1. -/
axiom field_Fpt (p : Nat) (hp : Nat.Prime p) : Field
axiom char_Fpt (p : Nat) (hp : Nat.Prime p) : characteristic (field_Fpt p hp) = p

/-- F_p(t) is NOT perfect: the polynomial x^p - t is irreducible but not
    separable (its derivative is 0 in characteristic p). -/
axiom Fpt_imperfect (p : Nat) (hp : Nat.Prime p) : ¬ isPerfect (field_Fpt p hp)

/-- The separable closure of F_p(t) is huge, containing t^{1/p^n}
    for all n (purely inseparable). -/
axiom Fpt_separable_closure (p : Nat) (hp : Nat.Prime p) : True

/-! ## Number fields — finite extensions of Q -/

/-- A number field is a finite extension of Q. Example: Q(√2) has degree 2. -/
axiom number_field_Q_sqrt2 : True  -- Q(√2), degree 2, Galois group Z/2Z

/-- Q(∛2) = Q(2^{1/3}) has degree 3, not Galois (the other two cube roots
    of 2 are complex and not in Q(∛2)). -/
axiom number_field_Q_cuberoot2 : True  -- Q(∛2), degree 3, NOT Galois

/-- Cyclotomic field Q(ζ_n) where ζ_n = e^{2πi/n} is the nth cyclotomic
    field. Degree φ(n), Galois over Q with Gal ≅ (Z/nZ)*. -/
axiom cyclotomic_field_Q_zeta_n (n : Nat) (hn : n > 0) : True
    -- Q(ζ_n), degree φ(n), Galois group (Z/nZ)×

/-- Q(√2, √3) has degree 4, Galois with group Z/2Z × Z/2Z (Klein four). -/
axiom biquadratic_field : True
    -- Q(√2, √3), degree 4, Gal(K/Q) ≅ V₄

/-! ## p-adic fields Q_p — characteristic 0, residue field F_p -/

/-- Q_p is the completion of Q with respect to the p-adic absolute value.
    Characteristic 0, but its residue field is F_p (characteristic p). -/
axiom field_Qp (p : Nat) (hp : Nat.Prime p) : Field
axiom char_Qp (p : Nat) (hp : Nat.Prime p) : characteristic (field_Qp p hp) = 0

/-- Q_p is a local field (locally compact, non-discrete topology). -/
axiom Qp_is_local_field (p : Nat) (hp : Nat.Prime p) : True

/-- Q_p is NOT algebraically closed. Its algebraic closure Q̄_p is
    infinite-dimensional and not complete. -/
axiom Qp_not_algebraically_closed (p : Nat) (hp : Nat.Prime p) :
    ¬ isAlgebraicallyClosed (field_Qp p hp)

/-- The completion of Q̄_p is C_p (p-adic complex numbers), which IS
    algebraically closed. -/
axiom Cp_algebraically_closed (p : Nat) (hp : Nat.Prime p) : True
    -- C_p is algebraically closed

/-! ## Algebraic closures — comparison -/

/-- The algebraic closure Q̄ (algebraic numbers) is countable. -/
axiom Qbar_countable : True
    -- |Q̄| = ℵ₀

/-- The algebraic closure F̄_p of a finite field is countable and
    equals ∪_{n≥1} F_{p^n}. -/
axiom Fpbar_countable_and_union (p : Nat) (hp : Nat.Prime p) : True
    -- F̄_p = ∪_{n≥1} F_{p^n}, countable

/-- The algebraic closure C of R is uncountable. -/
axiom C_uncountable_alg_closed : True

/-! ## #eval examples -/

#eval "Examples.Standard: field_Q — char 0 prime field, Q_is_frac_Z"
#eval "Examples.Standard: field_R — real closed, char 0, R_adjoin_i_is_C"
#eval "Examples.Standard: field_C — algebraically closed, char 0 (FTA)"
#eval "Examples.Standard: field_Fp — F_p = Z/pZ, prime, char p"
#eval "Examples.Standard: Fermat's Little Theorem over F_p"
#eval "Examples.Standard: field_Fpn — F_{p^n} char p, degree n over F_p"
#eval "Examples.Standard: F4 = {0,1,α,α+1}, F8, F9 examples"
#eval "Examples.Standard: field_Qt — Q(t) rational functions, char 0"
#eval "Examples.Standard: field_Fpt — F_p(t) characteristic p, NOT perfect"
#eval "Examples.Standard: Number fields: Q(√2), Q(∛2), Q(ζ_n), Q(√2,√3)"
#eval "Examples.Standard: Q_p — p-adic fields, char 0, residue field F_p"
#eval "Examples.Standard: Algebraic closures: Q̄ countable, F̄_p countable"

end MiniFieldTheoryCore
