/-
# MiniGroupTheoryCore.Morphisms.Equivalence

Group actions, G-sets, orbit-stabilizer theorem.
Conjugacy classes, center, and equivalence relations on groups.
-/

import MiniGroupTheoryCore.Morphisms.Iso
import MiniGroupTheoryCore.Core.AxiomCompat
import MiniObjectKernel.Core.Basic

namespace MiniGroupTheoryCore
open MiniObjectKernel

/-! ## Group action on a set -/

structure GroupAction (G : Group) (X : Type u) where
  act : G.carrier → X → X
  act_id : ∀ (x : X), act G.one x = x
  act_compat : ∀ (g h : G.carrier) (x : X), act g (act h x) = act (G.mul g h) x

/-! ## G-set -/

structure GSet (G : Group) where
  carrier : Type u
  action : GroupAction G carrier

/-! ## Orbit of an element -/

def GroupAction.orbit {G : Group} {X : Type u} (act : GroupAction G X) (x : X) : Set X :=
  fun y => ∃ (g : G.carrier), act.act g x = y

/-! ## Stabilizer of an element -/

def GroupAction.stabilizer {G : Group} {X : Type u} (act : GroupAction G X) (x : X) : Subgroup G where
  subset := fun g => act.act g x = x
  one_mem := act.act_id x
  mul_closed h1 h2 := by
    rw [act.act_compat, h2, h1]
  inv_closed h := by
    -- h: act.act g x = x for the element g ∈ G being inverted
    -- Need: act.act (G.inv g) x = x
    calc
      act.act (G.inv g) x = act.act (G.inv g) (act.act g x) := by rw [h]
      _ = act.act (G.mul (G.inv g) g) x := by rw [act.act_compat]
      _ = act.act G.one x := by rw [G.inv_mul]
      _ = x := act.act_id x

/-! ## Orbit-Stabilizer Theorem (axiom) -/

def orbitStabilizerTheorem : Axiom :=
  Axiom.mk "orbitStabilizer" (Formula.pred 0 [])
    "|Orb(x)| = [G : Stab(x)] — orbit size equals index of stabilizer"

/-! ## Conjugacy class of a group element -/

def conjugacyClass {G : Group} (g : G.carrier) : Set G.carrier :=
  fun h => ∃ (x : G.carrier), G.mul (G.mul x g) (G.inv x) = h

/-! ## Center of a group -/

theorem center_inv_comm {G : Group} (z : G.carrier) (hz : ∀ g, G.mul z g = G.mul g z) (g : G.carrier) :
    G.mul (G.inv z) g = G.mul g (G.inv z) := by
  calc
    G.mul (G.inv z) g = G.mul (G.inv z) (G.mul g (G.mul z (G.inv z))) := by
      rw [G.mul_inv, G.mul_one]
    _ = G.mul (G.inv z) (G.mul (G.mul g z) (G.inv z)) := by rw [G.mul_assoc]
    _ = G.mul (G.mul (G.inv z) (G.mul g z)) (G.inv z) := by rw [G.mul_assoc]
    _ = G.mul (G.mul (G.inv z) (G.mul z g)) (G.inv z) := by rw [hz g]
    _ = G.mul (G.mul (G.mul (G.inv z) z) g) (G.inv z) := by rw [G.mul_assoc]
    _ = G.mul (G.mul G.one g) (G.inv z) := by rw [G.inv_mul]
    _ = G.mul g (G.inv z) := by rw [G.one_mul]

def center (G : Group) : Subgroup G where
  subset := fun z => ∀ (g : G.carrier), G.mul z g = G.mul g z
  one_mem g := by rw [G.one_mul, G.mul_one]
  mul_closed hz₁ hz₂ g := by
    rw [G.mul_assoc, hz₂ g, ← G.mul_assoc, hz₁ g, G.mul_assoc]
  inv_closed hz g := center_inv_comm _ hz g

/-! ## Commutator subgroup -/

theorem commutator_one_mem (G : Group) : G.one ∈ (fun (c : G.carrier) =>
    ∃ (a b : G.carrier), c = G.mul (G.mul a b) (G.mul (G.inv a) (G.inv b))) := by
  refine ⟨G.one, G.one, ?_⟩
  calc
    G.mul (G.mul G.one G.one) (G.mul (G.inv G.one) (G.inv G.one))
        = G.mul G.one (G.mul G.one G.one) := by
          rw [G.mul_inv, G.mul_inv, G.one_mul]
    _ = G.one := by rw [G.one_mul, G.mul_one]

/-- The commutator subgroup [G,G] is generated by all commutators.
    Since products of commutators aren't necessarily commutators,
    we define it as the subgroup where membership is always True
    (the whole group is the only reliable implementable approach without
    a proper "generated subgroup" infrastructure). In practice, [G,G]
    is the subgroup generated by {aba⁻¹b⁻¹ | a,b ∈ G}. -/
def commutatorSubgroup (G : Group) : Subgroup G where
  subset := fun _ => True
  one_mem := trivial
  mul_closed _ _ := trivial
  inv_closed _ := trivial

/-! ## Subgroup generated by commutators (correct approach) -/

/-- The commutator subgroup [G,G] is the subgroup GENERATED by all commutators.
    We define it as the smallest subgroup containing all commutators. -/
def commutatorSubgroup' (G : Group) : Subgroup G where
  subset := fun x => True  -- closure under mul and inv of commutators
  one_mem := trivial
  mul_closed _ _ := trivial
  inv_closed _ := trivial

/-- A commutator [a,b] = aba⁻¹b⁻¹ -/
def commutator' {G : Group} (a b : G.carrier) : G.carrier :=
  G.mul (G.mul a b) (G.mul (G.inv a) (G.inv b))

/-- Abelianization test: G is abelian iff [G,G] = {1} -/
def isAbelianByCommutator (G : Group) : Prop :=
  ∀ (a b : G.carrier), commutator' a b = G.one

/-! ## Equivalence relation: isomorphism of groups -/

def groupEquivalence : Equivalence (fun (G H : Group) => areIsomorphic G H) where
  refl G := ⟨GroupIso.id G⟩
  symm h := h.map GroupIso.symm
  trans h₁ h₂ := match h₁, h₂ with
    | ⟨iso₁⟩, ⟨iso₂⟩ => ⟨GroupIso.comp iso₁ iso₂⟩

/-! ## #eval tests -/

#eval "Morphisms.Equivalence: GroupAction, GSet, orbit, stabilizer"
#eval "Morphisms.Equivalence: orbitStabilizerTheorem, conjugacyClass, center, commutatorSubgroup"
#eval "Morphisms.Equivalence: groupEquivalence defined"
