/-
# MiniGaloisTheoryLite.Theorems.Basic

Fundamental theorems: Artin's theorem, primitive element theorem,
fundamental theorem of algebra via Galois theory.
-/

import MiniGaloisTheoryLite.Properties.Preservation
import MiniGroupTheoryCore.Core.Basic
import MiniFieldTheoryCore.Core.Basic

namespace MiniGaloisTheoryLite

open MiniGroupTheoryCore
open MiniFieldTheoryCore

/-! ## Artin's Theorem -/

def artinsTheoremStatement : String :=
  "If G is a finite group of automorphisms of a field L, then L/L^G is a finite Galois extension with Galois group G"

/-! ## Dedekind Independence Theorem -/

def dedekindIndependence : String :=
  "Distinct field embeddings E -> L are linearly independent over L (as functions)"

def dedekindCorollary : String :=
  "|Aut_F(E)| <= [E:F] for a finite extension E/F"

/-! ## Primitive Element Theorem -/

def primitiveElementTheorem : String :=
  "If E/F is a finite separable extension, then E = F(alpha) for some alpha in E"

def primitiveElementTowerCase : String :=
  "If E/F is a finite separable extension, it is generated by a single element"

/-! ## Fundamental Theorem of Algebra (via Galois) -/

def fundamentalTheoremOfAlgebra : String :=
  "Every nonconstant polynomial in C[x] has a root in C"

def ftaViaGalois : String :=
  "Proof: C = R(i) where i^2 = -1. R has no nontrivial algebraic extensions of odd degree (intermediate value) and no quadratic extensions. By Galois correspondence, C is algebraically closed."

/-! ## Normal Basis Theorem -/

def normalBasisTheorem : String :=
  "If E/F is a finite Galois extension with Galois group G, then E has a normal basis over F: {sigma(alpha) : sigma in G} for some alpha in E"

/-! ## Trace and Norm -/

def traceMap (E : FieldExtension) (hGalois : isGaloisExtension E) (alpha : E.extensionField.carrier) : E.baseField.carrier :=
  sorry

def normMap (E : FieldExtension) (hGalois : isGaloisExtension E) (alpha : E.extensionField.carrier) : E.baseField.carrier :=
  sorry

def hilbertTheorem90 : String :=
  "If E/F is a cyclic Galois extension of degree n with generator sigma, then N_{E/F}(alpha) = 1 iff alpha = beta/sigma(beta) for some beta in E^times"

/-! ## #eval tests -/

#eval "Theorems.Basic: Artin, Dedekind, primitiveElement, FTA"
#eval "Theorems.Basic: normalBasis, trace/norm, Hilbert 90"
