/-
# MiniGaloisTheoryLite.Theorems.Classification

Fundamental Theorem of Galois Theory (full statement).
Solvability by radicals, insolvability of the quintic.
Cyclotomic extensions, finite fields, Kummer, Artin-Schreier.
-/

import MiniGaloisTheoryLite.Theorems.UniversalProperties
import MiniGroupTheoryCore.Core.Basic
import MiniFieldTheoryCore.Core.Basic

namespace MiniGaloisTheoryLite

open MiniGroupTheoryCore
open MiniFieldTheoryCore

/-! ## Fundamental Theorem of Galois Theory (full statement) -/

def fundamentalTheoremGalois : String :=
  "Let L/K be a finite Galois extension with G = Gal(L/K). Then there is a bijection:
   {intermediate fields K subset E subset L} <-> {subgroups H <= G}
   given by E |-> Gal(L/E) and H |-> L^H (fixed field).
   This bijection is order-reversing: E1 subset E2 iff Gal(L/E2) <= Gal(L/E1).
   Degree: [L:E] = |Gal(L/E)| and [E:K] = [G : Gal(L/E)].
   Normality: E/K is Galois iff Gal(L/E) is normal in G.
   In that case, Gal(E/K) ~= G / Gal(L/E)."

def galoisInclusionReversing : String :=
  "E1 subset E2 iff Gal(L/E2) <= Gal(L/E1). [L:E] = |Gal(L/E)| and [E:K] = [G : Gal(L/E)]"

def galoisNormalCorrespondence : String :=
  "E/K is normal (hence Galois) iff Gal(L/E) is normal in G. In this case, Gal(E/K) ~= G/Gal(L/E)"

/-! ## Solvability by radicals -/

def solvabilityByRadicals : String :=
  "A polynomial f in K[x] (char(K) = 0) is solvable by radicals iff its Galois group is solvable"

def insolvabilityOfQuintic : String :=
  "The general quintic equation is not solvable by radicals, because S5 is not solvable"

def solvabilityCriterion : String :=
  "A Galois extension E/F is a radical extension iff Gal(E/F) is solvable"

/-! ## Cyclotomic extensions -/

def cyclotomicGaloisGroup : String :=
  "Gal(Q(zeta_n)/Q) ~= (Z/nZ)^x for n >= 2. The extension is abelian of degree phi(n)"

def cyclotomicSubfields : String :=
  "Subfields of Q(zeta_n) correspond to subgroups of (Z/nZ)^x"

/-! ## Finite fields -/

def finiteFieldsClassification : String :=
  "For each prime p and n >= 1, there is exactly one finite field (up to iso) of order p^n. Its Galois group over F_p is cyclic of order n, generated by Frobenius x |-> x^p"

def finiteFieldGalois : String :=
  "Gal(F_{p^n}/F_p) ~= C_n, generated by Frobenius. Subfields correspond to divisors of n"

/-! ## Kummer theory -/

def kummerTheory : String :=
  "If K contains all n-th roots of unity, then abelian extensions of exponent n correspond to subgroups of K^x/(K^x)^n"

def kummerPairing : String :=
  "Gal(L/K) x (K^x cap (L^x)^n)/(K^x)^n -> mu_n is a perfect pairing"

/-! ## Artin-Schreier theory -/

def artinSchreierTheorem : String :=
  "Cyclic extensions of degree p in characteristic p are given by adjoining roots of x^p - x - a for a in K"

def artinSchreierWitt : String :=
  "General cyclic p^n-extensions in char p are described by Witt vectors"

/-! ## Rationality and Galois groups over Q -/

def inverseGaloisProblem : String :=
  "Is every finite group the Galois group of some Galois extension of Q? (Open)"

def knownGaloisGroupsOverQ : String :=
  "All abelian groups, S_n, A_n, all sporadic simple groups except possibly M23, many Lie type groups are Galois groups over Q"

/-! ## #eval tests -/

#eval "Theorems.Classification: FTGT (3 parts), solvabilityByRadicals, insolvabilityOfQuintic"
#eval "Theorems.Classification: cyclotomicGaloisGroup, finiteFieldsClassification, finiteFieldGalois"
#eval "Theorems.Classification: kummerTheory, artinSchreier, inverseGaloisProblem"
